from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text(encoding="utf-8")
    if new in text:
        return
    if old not in text:
        raise RuntimeError(f"Expected patch anchor not found in {path}: {old[:120]!r}")
    file.write_text(text.replace(old, new, 1), encoding="utf-8")


# -----------------------------------------------------------------------------
# FeedPost: preserve a dedicated username/handle alongside the display name.
# Keep it last with a default so older constructors/cached JSON remain compatible.
# -----------------------------------------------------------------------------
post_model = "app/src/main/java/com/example/data/models/PostModel.kt"
replace_once(
    post_model,
    '''    val adCta: String? = null,\n    val createdAt: String = ""\n)''',
    '''    val adCta: String? = null,\n    val createdAt: String = "",\n    val authorUsername: String = ""\n)'''
)


# -----------------------------------------------------------------------------
# Supabase parser: hydrate both display name and username when either/newer
# projection fields are present, while preserving legacy `author` records.
# -----------------------------------------------------------------------------
supabase = "app/src/main/java/com/example/data/supabase/SupabaseService.kt"
replace_once(
    supabase,
    '''    private fun parseFeedPost(obj: JSONObject): FeedPost {\n        val author = obj.cleanString("author").ifBlank { obj.cleanString("username") }\n''',
    '''    private fun parseFeedPost(obj: JSONObject): FeedPost {\n        val authorUsername = obj.cleanString("username")\n            .ifBlank { obj.cleanString("author_username") }\n            .ifBlank { obj.cleanString("author_handle") }\n            .removePrefix("@")\n            .trim()\n        val author = obj.cleanString("author_name")\n            .ifBlank { obj.cleanString("full_name") }\n            .ifBlank { obj.cleanString("author") }\n            .ifBlank { authorUsername }\n'''
)
replace_once(
    supabase,
    '''        return FeedPost(\n            id = obj.cleanString("id"),\n            author = author,\n            authorAvatar = obj.cleanString("author_avatar").ifBlank { obj.cleanString("avatar_url") },''',
    '''        return FeedPost(\n            id = obj.cleanString("id"),\n            author = author,\n            authorUsername = authorUsername.ifBlank { obj.cleanString("author").removePrefix("@").trim() },\n            authorAvatar = obj.cleanString("author_avatar").ifBlank { obj.cleanString("avatar_url") },'''
)


# -----------------------------------------------------------------------------
# PostCard: show display name + @username + exact verification tier, and only
# draw the gradient ring when the caller confirms that the author has a story.
# -----------------------------------------------------------------------------
post_card = "app/src/main/java/com/example/ui/components/PostCard.kt"
replace_once(
    post_card,
    '''    onVotePoll: (postId: String, optionId: String) -> Unit = { _, _ -> },\n    isAuthor: Boolean = false,\n    onDelete: () -> Unit = {},\n    modifier: Modifier = Modifier\n) {\n    val displayImages = remember(post.images) {''',
    '''    onVotePoll: (postId: String, optionId: String) -> Unit = { _, _ -> },\n    isAuthor: Boolean = false,\n    onDelete: () -> Unit = {},\n    authorName: String = post.author,\n    authorUsername: String = post.authorUsername.ifBlank { post.author },\n    authorVerificationBadge: VerificationBadge = when {\n        post.verificationBadge != VerificationBadge.NONE -> post.verificationBadge\n        post.isVerified -> VerificationBadge.BLUE\n        else -> VerificationBadge.NONE\n    },\n    hasActiveStory: Boolean = false,\n    modifier: Modifier = Modifier\n) {\n    val resolvedAuthorName = authorName.trim().ifBlank { post.author.trim() }\n    val resolvedAuthorUsername = authorUsername.trim().removePrefix("@").ifBlank {\n        post.authorUsername.trim().removePrefix("@").ifBlank { post.author.trim().removePrefix("@") }\n    }\n    val profileTarget = resolvedAuthorUsername.ifBlank { post.author }\n\n    val displayImages = remember(post.images) {'''
)

old_avatar = '''                Box(\n                    modifier = Modifier\n                        .size(50.dp)\n                        .background(\n                            Brush.linearGradient(\n                                listOf(FeedGradientStart, FeedGradientEnd)\n                            ),\n                            CircleShape\n                        )\n                        .padding(2.dp)\n                        .background(FeedCardSurface, CircleShape)\n                        .padding(2.dp)\n                        .clickable(role = Role.Button) { onProfileClick(post.author) }\n                ) {\n                    AsyncImage(\n                        model = post.authorAvatar,\n                        contentDescription = "${post.author} profile picture",\n                        contentScale = ContentScale.Crop,\n                        modifier = Modifier\n                            .fillMaxSize()\n                            .clip(CircleShape)\n                    )\n                }'''
new_avatar = '''                val avatarFrameModifier = if (hasActiveStory) {\n                    Modifier\n                        .size(50.dp)\n                        .background(\n                            Brush.linearGradient(\n                                listOf(FeedGradientStart, FeedGradientEnd)\n                            ),\n                            CircleShape\n                        )\n                        .padding(2.dp)\n                        .background(FeedCardSurface, CircleShape)\n                        .padding(2.dp)\n                } else {\n                    Modifier.size(50.dp)\n                }\n\n                Box(\n                    modifier = avatarFrameModifier\n                        .clip(CircleShape)\n                        .clickable(role = Role.Button) { onProfileClick(profileTarget) }\n                ) {\n                    AsyncImage(\n                        model = post.authorAvatar,\n                        contentDescription = "$resolvedAuthorName profile picture",\n                        contentScale = ContentScale.Crop,\n                        modifier = Modifier\n                            .fillMaxSize()\n                            .clip(CircleShape)\n                    )\n                }'''
replace_once(post_card, old_avatar, new_avatar)

old_identity = '''                Column(modifier = Modifier.weight(1f)) {\n                    Row(verticalAlignment = Alignment.CenterVertically) {\n                        Text(\n                            text = post.author,\n                            color = FeedTextPrimary,\n                            style = MaterialTheme.typography.titleMedium,\n                            maxLines = 1,\n                            overflow = TextOverflow.Ellipsis,\n                            modifier = Modifier.clickable { onProfileClick(post.author) }\n                        )\n                        if (post.isVerified || post.verificationBadge != VerificationBadge.NONE) {\n                            Spacer(Modifier.width(5.dp))\n                            Icon(\n                                imageVector = Icons.Default.Verified,\n                                contentDescription = "Verified",\n                                tint = when (post.verificationBadge) {\n                                    VerificationBadge.GOLD -> BlinkGold\n                                    else -> FeedBlue\n                                },\n                                modifier = Modifier.size(17.dp)\n                            )\n                        }\n                    }\n                    val meta = listOf(post.timeAgo, post.facultyTag)\n                        .filter(String::isNotBlank)\n                        .joinToString("  •  ")\n                    if (meta.isNotBlank()) {\n                        Text(\n                            text = meta,\n                            color = FeedTextSecondary,\n                            style = MaterialTheme.typography.bodyMedium,\n                            maxLines = 1,\n                            overflow = TextOverflow.Ellipsis\n                        )\n                    }\n                }'''
new_identity = '''                Column(modifier = Modifier.weight(1f)) {\n                    Row(verticalAlignment = Alignment.CenterVertically) {\n                        Text(\n                            text = resolvedAuthorName,\n                            color = FeedTextPrimary,\n                            style = MaterialTheme.typography.titleMedium,\n                            fontWeight = FontWeight.SemiBold,\n                            maxLines = 1,\n                            overflow = TextOverflow.Ellipsis,\n                            modifier = Modifier.clickable { onProfileClick(profileTarget) }\n                        )\n                        if (authorVerificationBadge != VerificationBadge.NONE) {\n                            Spacer(Modifier.width(5.dp))\n                            Icon(\n                                imageVector = Icons.Default.Verified,\n                                contentDescription = when (authorVerificationBadge) {\n                                    VerificationBadge.GOLD -> "Gold verified"\n                                    VerificationBadge.BLUE -> "Blue verified"\n                                    VerificationBadge.NONE -> null\n                                },\n                                tint = when (authorVerificationBadge) {\n                                    VerificationBadge.GOLD -> BlinkGold\n                                    VerificationBadge.BLUE -> FeedBlue\n                                    VerificationBadge.NONE -> FeedBlue\n                                },\n                                modifier = Modifier.size(17.dp)\n                            )\n                        }\n                    }\n                    val meta = listOf(\n                        resolvedAuthorUsername.takeIf(String::isNotBlank)?.let { "@$it" }.orEmpty(),\n                        post.timeAgo,\n                        post.facultyTag\n                    )\n                        .filter(String::isNotBlank)\n                        .joinToString("  •  ")\n                    if (meta.isNotBlank()) {\n                        Text(\n                            text = meta,\n                            color = FeedTextSecondary,\n                            style = MaterialTheme.typography.bodyMedium,\n                            maxLines = 1,\n                            overflow = TextOverflow.Ellipsis,\n                            modifier = Modifier.clickable { onProfileClick(profileTarget) }\n                        )\n                    }\n                }'''
replace_once(post_card, old_identity, new_identity)


# -----------------------------------------------------------------------------
# FeedScreen: resolve legacy posts through loaded profiles and derive the ring
# from the active stories returned by Supabase (`active=eq.true`).
# -----------------------------------------------------------------------------
feed = "app/src/main/java/com/example/ui/screens/FeedScreen.kt"
replace_once(
    feed,
    '''import com.example.data.models.LeaderboardUser\nimport com.example.ui.components.PostCard''',
    '''import com.example.data.models.LeaderboardUser\nimport com.example.data.models.VerificationBadge\nimport com.example.ui.components.PostCard'''
)
replace_once(
    feed,
    '''    val postIds = remember(posts) { posts.mapTo(linkedSetOf()) { it.id } }\n    // 0 = full header + tabs, 1 = compact utility header, 2 = hidden while scrolling.''',
    '''    val postIds = remember(posts) { posts.mapTo(linkedSetOf()) { it.id } }\n    val profilesByUsername = remember(profiles) {\n        profiles.asSequence()\n            .filter { it.username.isNotBlank() }\n            .associateBy { it.username.trim().removePrefix("@").lowercase() }\n    }\n    val profilesByName = remember(profiles) {\n        profiles.asSequence()\n            .filter { it.fullName.isNotBlank() }\n            .associateBy { it.fullName.trim().lowercase() }\n    }\n    val activeStoryUsernames = remember(stories) {\n        stories.asSequence()\n            .filterNot { it.id == "story_me" || it.username.isBlank() }\n            .map { it.username.trim().removePrefix("@").lowercase() }\n            .toSet()\n    }\n    // 0 = full header + tabs, 1 = compact utility header, 2 = hidden while scrolling.'''
)

old_item = '''                            ) { post ->\n                                Column {\n                                    PostCard(\n                                        post = post,\n                                        isDark = isDark,\n                                        onLike = { onLikePost(post.id) },\n                                        onComment = { onCommentPost(post.id) },\n                                        onBookmark = { onBookmarkPost(post.id) },\n                                        onRepost = { onRepostPost(post.id) },\n                                        onShare = { onSharePost(post.id) },\n                                        onOptionsClick = { onOptionsClick(post) },\n                                        onProfileClick = onProfileClick,\n                                        isAuthor = post.author.equals(currentUsername, true),\n                                        onDelete = { onDeletePost(post.id) },\n                                        onVotePoll = onVotePoll\n                                    )'''
new_item = '''                            ) { post ->\n                                val storedUsername = post.authorUsername.trim().removePrefix("@")\n                                val authorKey = storedUsername.ifBlank { post.author.trim().removePrefix("@") }.lowercase()\n                                val authorProfile = profilesByUsername[authorKey]\n                                    ?: profilesByName[post.author.trim().lowercase()]\n                                val resolvedUsername = authorProfile?.username\n                                    ?.trim()\n                                    ?.removePrefix("@")\n                                    ?.takeIf(String::isNotBlank)\n                                    ?: storedUsername.takeIf(String::isNotBlank)\n                                    ?: post.author.trim().removePrefix("@")\n                                val resolvedName = authorProfile?.fullName\n                                    ?.trim()\n                                    ?.takeIf(String::isNotBlank)\n                                    ?: post.author.trim().ifBlank { resolvedUsername }\n                                val resolvedBadge = authorProfile?.verificationBadge ?: when {\n                                    post.verificationBadge != VerificationBadge.NONE -> post.verificationBadge\n                                    post.isVerified -> VerificationBadge.BLUE\n                                    else -> VerificationBadge.NONE\n                                }\n                                val hasActiveStory = resolvedUsername.lowercase() in activeStoryUsernames\n\n                                Column {\n                                    PostCard(\n                                        post = post,\n                                        isDark = isDark,\n                                        onLike = { onLikePost(post.id) },\n                                        onComment = { onCommentPost(post.id) },\n                                        onBookmark = { onBookmarkPost(post.id) },\n                                        onRepost = { onRepostPost(post.id) },\n                                        onShare = { onSharePost(post.id) },\n                                        onOptionsClick = { onOptionsClick(post) },\n                                        onProfileClick = onProfileClick,\n                                        isAuthor = resolvedUsername.equals(currentUsername.removePrefix("@"), true),\n                                        onDelete = { onDeletePost(post.id) },\n                                        onVotePoll = onVotePoll,\n                                        authorName = resolvedName,\n                                        authorUsername = resolvedUsername,\n                                        authorVerificationBadge = resolvedBadge,\n                                        hasActiveStory = hasActiveStory\n                                    )'''
replace_once(feed, old_item, new_item)

print("Applied post identity, verification and active-story avatar ring fixes.")
