with open('app/src/main/java/com/example/data/models/UserProfileModel.kt', 'r') as f:
    content = f.read()

# Make the dummy data empty by default to prevent hardcoded demo data from polluting real users
content = content.replace('var avatarUrl: String = "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop"', 'var avatarUrl: String = ""')
content = content.replace('var coverPhotoUrl: String = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&h=400&fit=crop"', 'var coverPhotoUrl: String = ""')
content = content.replace('var verificationBadge: VerificationBadge = VerificationBadge.BLUE', 'var verificationBadge: VerificationBadge = VerificationBadge.NONE')
content = content.replace('var professionalHeadline: String = "Product Designer • Creative Technologist"', 'var professionalHeadline: String = ""')
content = content.replace('var currentJobTitle: String = "UI/UX Lead at CampusDev"', 'var currentJobTitle: String = ""')
content = content.replace('var university: String = "University of Lagos (UNILAG)"', 'var university: String = ""')
content = content.replace('var faculty: String = "Engineering"', 'var faculty: String = ""')
content = content.replace('var department: String = "Systems Engineering"', 'var department: String = ""')
content = content.replace('var courseOfStudy: String = "B.Sc. Systems Engineering"', 'var courseOfStudy: String = ""')
content = content.replace('var academicLevel: String = "400 Level"', 'var academicLevel: String = ""')
content = content.replace('var graduationYear: String = "Class of 2027"', 'var graduationYear: String = ""')
content = content.replace('var bio: String = "Crafting digital experiences, campus entrepreneurship, building for the next billion users 🚀✨"', 'var bio: String = ""')
content = content.replace('var availability: AvailabilityStatus = AvailabilityStatus.AVAILABLE_FOR_FREELANCE', 'var availability: AvailabilityStatus = AvailabilityStatus.NONE')
content = content.replace('var countryOfOrigin: String = "🇳🇬 Nigeria"', 'var countryOfOrigin: String = ""')
content = content.replace('var currentCityState: String = "Lagos, Nigeria"', 'var currentCityState: String = ""')
content = content.replace('var email: ContactField = ContactField("efe.chukwu@student.unilag.edu.ng", true)', 'var email: ContactField = ContactField("", true)')
content = content.replace('var phone: ContactField = ContactField("+234 809 123 4567", true)', 'var phone: ContactField = ContactField("", false)')
content = content.replace('var whatsapp: ContactField = ContactField("+234 809 123 4567", true)', 'var whatsapp: ContactField = ContactField("", false)')
content = content.replace('var coreSkills: MutableList<String> = mutableListOf("Product Design", "Figma", "Jetpack Compose", "Kotlin", "Prototyping", "Aluta Commerce")', 'var coreSkills: MutableList<String> = mutableListOf()')
content = content.replace('var skillEndorsements: MutableList<SkillEndorsement> = mutableListOf(\n        SkillEndorsement("Product Design", 48, false),\n        SkillEndorsement("Figma", 62, true),\n        SkillEndorsement("Jetpack Compose", 35, false),\n        SkillEndorsement("Kotlin", 29, false)\n    )', 'var skillEndorsements: MutableList<SkillEndorsement> = mutableListOf()')
content = content.replace('var hobbies: List<String> = listOf("Photography", "Tech Meetups", "Gaming", "Afrobeats", "Football")', 'var hobbies: List<String> = listOf()')
content = content.replace('var languages: List<String> = listOf("English", "Yoruba", "Pidgin")', 'var languages: List<String> = listOf()')
content = content.replace('var favoriteQuote: String = "The best way to predict the future is to build it."', 'var favoriteQuote: String = ""')
content = content.replace('var dailyStreak: Int = 5', 'var dailyStreak: Int = 0')
content = content.replace('var worldRank: Int = 142', 'var worldRank: Int = 0')
content = content.replace('var campusRank: Int = 12', 'var campusRank: Int = 0')
content = content.replace('var onlineNow: Boolean = true', 'var onlineNow: Boolean = false')
content = content.replace('var joinedLabel: String = "Joined Blink in October 2024"', 'var joinedLabel: String = ""')
content = content.replace('var isSellerActive: Boolean = true', 'var isSellerActive: Boolean = false')
content = content.replace('var sellerStoreName: String = "Efe Tech Hub & Gadgets"', 'var sellerStoreName: String = ""')
content = content.replace('var badges: List<AchievementBadge> = listOf(\n        AchievementBadge("top_creator", "Top Creator", "Top 1% engagement in UNILAG"),\n        AchievementBadge("verified_seller", "Verified Merchant", "50+ 5-star sales on Aluta Market"),\n        AchievementBadge("streak_master", "20-Day Streak", "Consistent campus contributor")\n    )', 'var badges: List<AchievementBadge> = listOf()')

with open('app/src/main/java/com/example/data/models/UserProfileModel.kt', 'w') as f:
    f.write(content)

