-- Blink Supabase recovery snapshot: private/private_ranking constraints
ALTER TABLE private.admin_action_reversals ADD CONSTRAINT admin_action_reversals_action_id_fkey FOREIGN KEY (action_id) REFERENCES private.admin_audit_log(id) ON DELETE CASCADE;
ALTER TABLE private.admin_action_reversals ADD CONSTRAINT admin_action_reversals_pkey PRIMARY KEY (action_id);
ALTER TABLE private.admin_action_reversals ADD CONSTRAINT admin_action_reversals_reversed_by_fkey FOREIGN KEY (reversed_by) REFERENCES auth.users(id);
ALTER TABLE private.admin_announcements ADD CONSTRAINT admin_announcements_pkey PRIMARY KEY (id);
ALTER TABLE private.admin_announcements ADD CONSTRAINT admin_announcements_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private.admin_announcements ADD CONSTRAINT admin_announcements_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.admin_announcements ADD CONSTRAINT admin_announcements_verification_filter_check CHECK (verification_filter = ANY (ARRAY['all'::text, 'blue'::text, 'gold'::text]));
ALTER TABLE private.admin_audit_log ADD CONSTRAINT admin_audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private.admin_audit_log ADD CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id);
ALTER TABLE private.admin_audit_log ADD CONSTRAINT admin_audit_log_target_post_id_fkey FOREIGN KEY (target_post_id) REFERENCES feed_posts(id) ON DELETE SET NULL;
ALTER TABLE private.admin_audit_log ADD CONSTRAINT admin_audit_log_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.admin_coin_transactions ADD CONSTRAINT admin_coin_transactions_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE private.admin_coin_transactions ADD CONSTRAINT admin_coin_transactions_pkey PRIMARY KEY (id);
ALTER TABLE private.admin_coin_transactions ADD CONSTRAINT admin_coin_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.admin_comment_state ADD CONSTRAINT admin_comment_state_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE;
ALTER TABLE private.admin_comment_state ADD CONSTRAINT admin_comment_state_pkey PRIMARY KEY (comment_id);
ALTER TABLE private.admin_comment_state ADD CONSTRAINT admin_comment_state_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.admin_feature_catalog ADD CONSTRAINT admin_feature_catalog_category_check CHECK (category = ANY (ARRAY['users'::text, 'admins'::text, 'coins'::text, 'verification'::text, 'content'::text, 'messages'::text, 'analytics'::text, 'system'::text]));
ALTER TABLE private.admin_feature_catalog ADD CONSTRAINT admin_feature_catalog_feature_id_check CHECK (feature_id >= 1 AND feature_id <= 200);
ALTER TABLE private.admin_feature_catalog ADD CONSTRAINT admin_feature_catalog_pkey PRIMARY KEY (feature_id);
ALTER TABLE private.admin_feature_registry_v2 ADD CONSTRAINT admin_feature_registry_v2_pkey PRIMARY KEY (feature_id);
ALTER TABLE private.admin_feature_registry_v2 ADD CONSTRAINT admin_feature_registry_v2_route_key_key UNIQUE (route_key);
ALTER TABLE private.admin_notes ADD CONSTRAINT admin_notes_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE private.admin_notes ADD CONSTRAINT admin_notes_note_check CHECK (char_length(note) >= 1 AND char_length(note) <= 4000);
ALTER TABLE private.admin_notes ADD CONSTRAINT admin_notes_pkey PRIMARY KEY (id);
ALTER TABLE private.admin_notes ADD CONSTRAINT admin_notes_target_admin_id_fkey FOREIGN KEY (target_admin_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.admin_notes ADD CONSTRAINT admin_notes_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.admin_notification_campaigns ADD CONSTRAINT admin_notification_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE private.admin_notification_campaigns ADD CONSTRAINT admin_notification_campaigns_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE private.admin_notification_campaigns ADD CONSTRAINT admin_notification_campaigns_status_check CHECK (status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'sending'::text, 'sent'::text, 'cancelled'::text, 'failed'::text]));
ALTER TABLE private.admin_notification_deliveries ADD CONSTRAINT admin_notification_deliveries_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES private.admin_notification_campaigns(id) ON DELETE CASCADE;
ALTER TABLE private.admin_notification_deliveries ADD CONSTRAINT admin_notification_deliveries_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE SET NULL;
ALTER TABLE private.admin_notification_deliveries ADD CONSTRAINT admin_notification_deliveries_pkey PRIMARY KEY (campaign_id, user_id);
ALTER TABLE private.admin_notification_deliveries ADD CONSTRAINT admin_notification_deliveries_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.admin_report_state ADD CONSTRAINT admin_report_state_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.admin_report_state ADD CONSTRAINT admin_report_state_pkey PRIMARY KEY (report_id);
ALTER TABLE private.admin_report_state ADD CONSTRAINT admin_report_state_report_id_fkey FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE;
ALTER TABLE private.admin_report_state ADD CONSTRAINT admin_report_state_severity_check CHECK (severity = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'critical'::text]));
ALTER TABLE private.admin_report_state ADD CONSTRAINT admin_report_state_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.admin_role_templates ADD CONSTRAINT admin_role_templates_pkey PRIMARY KEY (template_key);
ALTER TABLE private.admin_roles ADD CONSTRAINT admin_roles_check CHECK (role = 'owner'::text OR expires_at IS NULL OR expires_at > granted_at);
ALTER TABLE private.admin_roles ADD CONSTRAINT admin_roles_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.admin_roles ADD CONSTRAINT admin_roles_pkey PRIMARY KEY (user_id);
ALTER TABLE private.admin_roles ADD CONSTRAINT admin_roles_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text]));
ALTER TABLE private.admin_roles ADD CONSTRAINT admin_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private.admin_sections_v3 ADD CONSTRAINT admin_sections_v3_pkey PRIMARY KEY (section_key);
ALTER TABLE private.admin_sections_v3 ADD CONSTRAINT admin_sections_v3_sort_order_key UNIQUE (sort_order);
ALTER TABLE private.admin_system_config ADD CONSTRAINT admin_system_config_pkey PRIMARY KEY (key);
ALTER TABLE private.admin_system_config ADD CONSTRAINT admin_system_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.admin_university_catalog ADD CONSTRAINT admin_university_catalog_pkey PRIMARY KEY (name);
ALTER TABLE private.admin_user_controls ADD CONSTRAINT admin_user_controls_pkey PRIMARY KEY (user_id);
ALTER TABLE private.admin_user_controls ADD CONSTRAINT admin_user_controls_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.admin_user_controls ADD CONSTRAINT admin_user_controls_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.content_view_events ADD CONSTRAINT content_view_events_content_type_check CHECK (content_type = ANY (ARRAY['post'::text, 'reel'::text]));
ALTER TABLE private.content_view_events ADD CONSTRAINT content_view_events_pkey PRIMARY KEY (event_id);
ALTER TABLE private.content_view_events ADD CONSTRAINT content_view_events_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE private.content_view_events ADD CONSTRAINT content_view_events_view_weight_check CHECK (view_weight = ANY (ARRAY[1, 3, 6]));
ALTER TABLE private.content_view_events ADD CONSTRAINT content_view_events_viewer_id_fkey FOREIGN KEY (viewer_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private.user_streak_state ADD CONSTRAINT user_streak_state_current_streak_check CHECK (current_streak >= 0);
ALTER TABLE private.user_streak_state ADD CONSTRAINT user_streak_state_pkey PRIMARY KEY (user_id);
ALTER TABLE private.user_streak_state ADD CONSTRAINT user_streak_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.web_content_views ADD CONSTRAINT web_content_views_impression_count_check CHECK (impression_count >= 0 AND impression_count <= 100);
ALTER TABLE private.web_content_views ADD CONSTRAINT web_content_views_pkey PRIMARY KEY (post_id, visitor_hash);
ALTER TABLE private.web_content_views ADD CONSTRAINT web_content_views_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE private.web_content_views ADD CONSTRAINT web_content_views_visitor_hash_length_check CHECK (char_length(visitor_hash) >= 32 AND char_length(visitor_hash) <= 128);
ALTER TABLE private_ranking.discovery_interest_cache ADD CONSTRAINT discovery_interest_cache_pkey PRIMARY KEY (user_id);
ALTER TABLE private_ranking.discovery_interest_cache ADD CONSTRAINT discovery_interest_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private_ranking.discovery_reel_metrics ADD CONSTRAINT discovery_reel_metrics_completion_rate_check CHECK (completion_rate >= 0::numeric AND completion_rate <= 1::numeric);
ALTER TABLE private_ranking.discovery_reel_metrics ADD CONSTRAINT discovery_reel_metrics_completion_samples_check CHECK (completion_samples >= 0);
ALTER TABLE private_ranking.discovery_reel_metrics ADD CONSTRAINT discovery_reel_metrics_pkey PRIMARY KEY (post_id);
ALTER TABLE private_ranking.discovery_reel_metrics ADD CONSTRAINT discovery_reel_metrics_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE private_ranking.discovery_user_geo ADD CONSTRAINT discovery_user_geo_pkey PRIMARY KEY (user_id);
ALTER TABLE private_ranking.discovery_user_geo ADD CONSTRAINT discovery_user_geo_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private_ranking.discovery_verification_multipliers ADD CONSTRAINT discovery_verification_multipliers_multiplier_check CHECK (multiplier > 0::numeric);
ALTER TABLE private_ranking.discovery_verification_multipliers ADD CONSTRAINT discovery_verification_multipliers_pkey PRIMARY KEY (tier);
