-- Blink Supabase recovery snapshot: public constraints A-M
ALTER TABLE public.activities ADD CONSTRAINT activities_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.activities ADD CONSTRAINT activities_pkey PRIMARY KEY (id);
ALTER TABLE public.activities ADD CONSTRAINT activities_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_boost_touches ADD CONSTRAINT blink_boost_touches_boost_id_fkey FOREIGN KEY (boost_id) REFERENCES blink_boosts(id) ON DELETE CASCADE;
ALTER TABLE public.blink_boost_touches ADD CONSTRAINT blink_boost_touches_pkey PRIMARY KEY (boost_id, viewer_id);
ALTER TABLE public.blink_boost_touches ADD CONSTRAINT blink_boost_touches_viewer_id_fkey FOREIGN KEY (viewer_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_boosts ADD CONSTRAINT blink_boosts_check CHECK (ends_at > starts_at);
ALTER TABLE public.blink_boosts ADD CONSTRAINT blink_boosts_content_id_fkey FOREIGN KEY (content_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.blink_boosts ADD CONSTRAINT blink_boosts_content_type_check CHECK (content_type = ANY (ARRAY['POST'::text, 'REEL'::text]));
ALTER TABLE public.blink_boosts ADD CONSTRAINT blink_boosts_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES blink_inventory(id) ON DELETE SET NULL;
ALTER TABLE public.blink_boosts ADD CONSTRAINT blink_boosts_multiplier_check CHECK (multiplier = ANY (ARRAY[1, 2, 3, 5]));
ALTER TABLE public.blink_boosts ADD CONSTRAINT blink_boosts_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_boosts ADD CONSTRAINT blink_boosts_status_check CHECK (status = ANY (ARRAY['ACTIVE'::text, 'ENDED'::text, 'CANCELLED'::text]));
ALTER TABLE public.blink_boosts ADD CONSTRAINT blink_boosts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_coin_gifts ADD CONSTRAINT blink_coin_gifts_amount_check CHECK (amount >= 1 AND amount <= 1000);
ALTER TABLE public.blink_coin_gifts ADD CONSTRAINT blink_coin_gifts_not_self CHECK (sender_id <> receiver_id);
ALTER TABLE public.blink_coin_gifts ADD CONSTRAINT blink_coin_gifts_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_coin_gifts ADD CONSTRAINT blink_coin_gifts_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.blink_coin_gifts ADD CONSTRAINT blink_coin_gifts_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.blink_coin_transactions ADD CONSTRAINT blink_coin_transactions_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES blink_store_catalog(id);
ALTER TABLE public.blink_coin_transactions ADD CONSTRAINT blink_coin_transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_coin_transactions ADD CONSTRAINT blink_coin_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_digital_gifts ADD CONSTRAINT blink_digital_gifts_check CHECK (sender_id <> recipient_id);
ALTER TABLE public.blink_digital_gifts ADD CONSTRAINT blink_digital_gifts_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES blink_inventory(id) ON DELETE SET NULL;
ALTER TABLE public.blink_digital_gifts ADD CONSTRAINT blink_digital_gifts_message_check CHECK (message IS NULL OR char_length(message) <= 200);
ALTER TABLE public.blink_digital_gifts ADD CONSTRAINT blink_digital_gifts_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_digital_gifts ADD CONSTRAINT blink_digital_gifts_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_digital_gifts ADD CONSTRAINT blink_digital_gifts_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_equipped_items ADD CONSTRAINT blink_equipped_items_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES blink_store_catalog(id);
ALTER TABLE public.blink_equipped_items ADD CONSTRAINT blink_equipped_items_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES blink_inventory(id) ON DELETE CASCADE;
ALTER TABLE public.blink_equipped_items ADD CONSTRAINT blink_equipped_items_pkey PRIMARY KEY (user_id, slot);
ALTER TABLE public.blink_equipped_items ADD CONSTRAINT blink_equipped_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_inventory ADD CONSTRAINT blink_inventory_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES blink_store_catalog(id);
ALTER TABLE public.blink_inventory ADD CONSTRAINT blink_inventory_gifted_by_fkey FOREIGN KEY (gifted_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.blink_inventory ADD CONSTRAINT blink_inventory_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_inventory ADD CONSTRAINT blink_inventory_quantity_check CHECK (quantity > 0);
ALTER TABLE public.blink_inventory ADD CONSTRAINT blink_inventory_status_check CHECK (status = ANY (ARRAY['AVAILABLE'::text, 'ACTIVE'::text, 'PERMANENT'::text, 'USED'::text, 'EXPIRED'::text]));
ALTER TABLE public.blink_inventory ADD CONSTRAINT blink_inventory_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_item_activations ADD CONSTRAINT blink_item_activations_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES blink_store_catalog(id);
ALTER TABLE public.blink_item_activations ADD CONSTRAINT blink_item_activations_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES blink_inventory(id) ON DELETE SET NULL;
ALTER TABLE public.blink_item_activations ADD CONSTRAINT blink_item_activations_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_item_activations ADD CONSTRAINT blink_item_activations_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_store_catalog ADD CONSTRAINT blink_store_catalog_item_type_check CHECK (item_type = ANY (ARRAY['CONSUMABLE'::text, 'TIMED'::text, 'PERMANENT'::text, 'CONTENT_SPECIFIC'::text, 'PASS'::text]));
ALTER TABLE public.blink_store_catalog ADD CONSTRAINT blink_store_catalog_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_store_catalog ADD CONSTRAINT blink_store_catalog_price_check CHECK (price >= 0);
ALTER TABLE public.blink_store_catalog ADD CONSTRAINT blink_store_catalog_target_type_check CHECK (target_type = ANY (ARRAY['NONE'::text, 'PROFILE'::text, 'POST'::text, 'REEL'::text, 'COMMENT'::text, 'CHAT'::text, 'MARKETPLACE'::text, 'APP'::text]));
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_marketplace_highlights_check CHECK (marketplace_highlights >= 0);
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_pass_id_fkey FOREIGN KEY (pass_id) REFERENCES blink_vip_passes(id) ON DELETE CASCADE;
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_pkey PRIMARY KEY (pass_id);
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_post_boosts_2x_check CHECK (post_boosts_2x >= 0);
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_post_spotlights_check CHECK (post_spotlights >= 0);
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_profile_spotlights_check CHECK (profile_spotlights >= 0);
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_reel_boosts_2x_check CHECK (reel_boosts_2x >= 0);
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_reel_spotlights_check CHECK (reel_spotlights >= 0);
ALTER TABLE public.blink_vip_benefit_balances ADD CONSTRAINT blink_vip_benefit_balances_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_vip_claims ADD CONSTRAINT blink_vip_claims_pass_id_fkey FOREIGN KEY (pass_id) REFERENCES blink_vip_passes(id) ON DELETE CASCADE;
ALTER TABLE public.blink_vip_claims ADD CONSTRAINT blink_vip_claims_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_vip_claims ADD CONSTRAINT blink_vip_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blink_vip_passes ADD CONSTRAINT blink_vip_passes_check CHECK (expires_at > starts_at);
ALTER TABLE public.blink_vip_passes ADD CONSTRAINT blink_vip_passes_gifted_by_fkey FOREIGN KEY (gifted_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.blink_vip_passes ADD CONSTRAINT blink_vip_passes_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES blink_inventory(id) ON DELETE SET NULL;
ALTER TABLE public.blink_vip_passes ADD CONSTRAINT blink_vip_passes_pkey PRIMARY KEY (id);
ALTER TABLE public.blink_vip_passes ADD CONSTRAINT blink_vip_passes_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.blocks ADD CONSTRAINT blocks_pkey PRIMARY KEY (blocker_id, blocked_id);
ALTER TABLE public.blocks ADD CONSTRAINT no_self_block CHECK (blocker_id <> blocked_id);
ALTER TABLE public.call_push_dispatches ADD CONSTRAINT call_push_dispatches_attempts_check CHECK (attempts > 0);
ALTER TABLE public.call_push_dispatches ADD CONSTRAINT call_push_dispatches_call_id_fkey FOREIGN KEY (call_id) REFERENCES calls(id) ON DELETE CASCADE;
ALTER TABLE public.call_push_dispatches ADD CONSTRAINT call_push_dispatches_pkey PRIMARY KEY (call_id, event, target_user_id);
ALTER TABLE public.call_push_dispatches ADD CONSTRAINT call_push_dispatches_status_check CHECK (status = ANY (ARRAY['sending'::text, 'sent'::text, 'failed'::text]));
ALTER TABLE public.call_push_dispatches ADD CONSTRAINT call_push_dispatches_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.call_signals ADD CONSTRAINT call_signals_call_id_fkey FOREIGN KEY (call_id) REFERENCES calls(id) ON DELETE CASCADE;
ALTER TABLE public.call_signals ADD CONSTRAINT call_signals_kind_check CHECK (kind = ANY (ARRAY['offer'::text, 'answer'::text, 'ice'::text, 'renegotiate'::text, 'hangup'::text]));
ALTER TABLE public.call_signals ADD CONSTRAINT call_signals_pkey PRIMARY KEY (id);
ALTER TABLE public.call_signals ADD CONSTRAINT call_signals_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.calls ADD CONSTRAINT calls_call_type_check CHECK (call_type = ANY (ARRAY['audio'::text, 'video'::text]));
ALTER TABLE public.calls ADD CONSTRAINT calls_callee_id_fkey FOREIGN KEY (callee_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.calls ADD CONSTRAINT calls_caller_id_fkey FOREIGN KEY (caller_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.calls ADD CONSTRAINT calls_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.calls ADD CONSTRAINT calls_distinct_users CHECK (caller_id <> callee_id);
ALTER TABLE public.calls ADD CONSTRAINT calls_duration_seconds_check CHECK (duration_seconds >= 0);
ALTER TABLE public.calls ADD CONSTRAINT calls_ended_by_fkey FOREIGN KEY (ended_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.calls ADD CONSTRAINT calls_pkey PRIMARY KEY (id);
ALTER TABLE public.calls ADD CONSTRAINT calls_status_check CHECK (status = ANY (ARRAY['ringing'::text, 'connecting'::text, 'connected'::text, 'declined'::text, 'busy'::text, 'missed'::text, 'cancelled'::text, 'ended'::text, 'failed'::text]));
ALTER TABLE public.comment_likes ADD CONSTRAINT comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE;
ALTER TABLE public.comment_likes ADD CONSTRAINT comment_likes_comment_id_user_id_key UNIQUE (comment_id, user_id);
ALTER TABLE public.comment_likes ADD CONSTRAINT comment_likes_pkey PRIMARY KEY (id);
ALTER TABLE public.comment_likes ADD CONSTRAINT comment_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.comment_mentions ADD CONSTRAINT comment_mentions_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE;
ALTER TABLE public.comment_mentions ADD CONSTRAINT comment_mentions_mentioned_user_id_fkey FOREIGN KEY (mentioned_user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.comment_mentions ADD CONSTRAINT comment_mentions_pkey PRIMARY KEY (comment_id, mentioned_user_id);
ALTER TABLE public.comment_replies ADD CONSTRAINT comment_replies_pkey PRIMARY KEY (id);
ALTER TABLE public.comments ADD CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.comments ADD CONSTRAINT comments_content_length_check CHECK (char_length(btrim(content)) >= 1 AND char_length(btrim(content)) <= 2000);
ALTER TABLE public.comments ADD CONSTRAINT comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES comments(id) ON DELETE CASCADE;
ALTER TABLE public.comments ADD CONSTRAINT comments_pkey PRIMARY KEY (id);
ALTER TABLE public.comments ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.connect_applications ADD CONSTRAINT connect_applications_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.connect_applications ADD CONSTRAINT connect_applications_listing_id_applicant_id_key UNIQUE (listing_id, applicant_id);
ALTER TABLE public.connect_applications ADD CONSTRAINT connect_applications_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES connect_listings(id) ON DELETE CASCADE;
ALTER TABLE public.connect_applications ADD CONSTRAINT connect_applications_message_check CHECK (char_length(message) <= 500);
ALTER TABLE public.connect_applications ADD CONSTRAINT connect_applications_pkey PRIMARY KEY (id);
ALTER TABLE public.connect_applications ADD CONSTRAINT connect_applications_status_check CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'withdrawn'::text]));
ALTER TABLE public.connect_category_catalog ADD CONSTRAINT connect_category_catalog_display_order_check CHECK (display_order >= 1 AND display_order <= 100);
ALTER TABLE public.connect_category_catalog ADD CONSTRAINT connect_category_catalog_display_order_key UNIQUE (display_order);
ALTER TABLE public.connect_category_catalog ADD CONSTRAINT connect_category_catalog_pkey PRIMARY KEY (id);
ALTER TABLE public.connect_category_catalog ADD CONSTRAINT connect_category_catalog_route_kind_check CHECK (route_kind = ANY (ARRAY['roommate'::text, 'mentor'::text, 'reading'::text, 'agents'::text, 'housing'::text, 'challenges'::text]));
ALTER TABLE public.connect_category_catalog ADD CONSTRAINT connect_category_catalog_slug_check CHECK (slug ~ '^[a-z0-9_]+$'::text);
ALTER TABLE public.connect_category_catalog ADD CONSTRAINT connect_category_catalog_slug_key UNIQUE (slug);
ALTER TABLE public.connect_listings ADD CONSTRAINT connect_listings_budget_max_check CHECK (budget_max IS NULL OR budget_max >= 0::numeric);
ALTER TABLE public.connect_listings ADD CONSTRAINT connect_listings_budget_min_check CHECK (budget_min IS NULL OR budget_min >= 0::numeric);
ALTER TABLE public.connect_listings ADD CONSTRAINT connect_listings_check CHECK (budget_min IS NULL OR budget_max IS NULL OR budget_max >= budget_min);
ALTER TABLE public.connect_listings ADD CONSTRAINT connect_listings_description_check CHECK (char_length(description) <= 800);
ALTER TABLE public.connect_listings ADD CONSTRAINT connect_listings_listing_type_check CHECK (listing_type = ANY (ARRAY['roommate'::text, 'housing_need'::text, 'housing_agent'::text, 'mentor_available'::text, 'mentor_needed'::text, 'study_mate'::text, 'project_partner'::text, 'skill_swap'::text, 'campus_guide'::text]));
ALTER TABLE public.connect_listings ADD CONSTRAINT connect_listings_pkey PRIMARY KEY (id);
ALTER TABLE public.connect_listings ADD CONSTRAINT connect_listings_title_check CHECK (char_length(btrim(title)) >= 3 AND char_length(btrim(title)) <= 90);
ALTER TABLE public.connect_listings ADD CONSTRAINT connect_listings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.connect_match_spins ADD CONSTRAINT connect_match_spins_coins_spent_check CHECK (coins_spent = 10);
ALTER TABLE public.connect_match_spins ADD CONSTRAINT connect_match_spins_compatibility_score_check CHECK (compatibility_score >= 0 AND compatibility_score <= 100);
ALTER TABLE public.connect_match_spins ADD CONSTRAINT connect_match_spins_matched_user_id_fkey FOREIGN KEY (matched_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.connect_match_spins ADD CONSTRAINT connect_match_spins_pkey PRIMARY KEY (id);
ALTER TABLE public.connect_match_spins ADD CONSTRAINT connect_match_spins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.connection_requests ADD CONSTRAINT connection_requests_check CHECK (sender_id <> receiver_id);
ALTER TABLE public.connection_requests ADD CONSTRAINT connection_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.connection_requests ADD CONSTRAINT connection_requests_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.connection_requests ADD CONSTRAINT connection_requests_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.connection_requests ADD CONSTRAINT connection_requests_status_check CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'cancelled'::text, 'blocked'::text]));
ALTER TABLE public.conversation_participants ADD CONSTRAINT conversation_participants_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_participants ADD CONSTRAINT conversation_participants_pkey PRIMARY KEY (conversation_id, user_id);
ALTER TABLE public.conversation_participants ADD CONSTRAINT conversation_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_reports ADD CONSTRAINT conversation_reports_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_reports ADD CONSTRAINT conversation_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.conversation_reports ADD CONSTRAINT conversation_reports_reason_check CHECK (char_length(reason) >= 1 AND char_length(reason) <= 500);
ALTER TABLE public.conversation_reports ADD CONSTRAINT conversation_reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_settings ADD CONSTRAINT conversation_settings_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_settings ADD CONSTRAINT conversation_settings_disappearing_seconds_check CHECK (disappearing_seconds >= 0 AND disappearing_seconds <= 2592000);
ALTER TABLE public.conversation_settings ADD CONSTRAINT conversation_settings_pkey PRIMARY KEY (conversation_id, user_id);
ALTER TABLE public.conversation_settings ADD CONSTRAINT conversation_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_user_state ADD CONSTRAINT conversation_user_state_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_user_state ADD CONSTRAINT conversation_user_state_pkey PRIMARY KEY (conversation_id, user_id);
ALTER TABLE public.conversation_user_state ADD CONSTRAINT conversation_user_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);
ALTER TABLE public.fcm_tokens ADD CONSTRAINT fcm_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.fcm_tokens ADD CONSTRAINT fcm_tokens_platform_check CHECK (platform = ANY (ARRAY['android'::text, 'ios'::text, 'web'::text, 'other'::text]));
ALTER TABLE public.fcm_tokens ADD CONSTRAINT fcm_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.fcm_tokens ADD CONSTRAINT fcm_tokens_user_id_token_key UNIQUE (user_id, token);
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_active_content_required CHECK (NOT is_active OR COALESCE(NULLIF(btrim(text), ''::text), NULLIF(btrim(caption), ''::text)) IS NOT NULL OR cardinality(COALESCE(images, '{}'::text[])) > 0 OR COALESCE(NULLIF(btrim(image_url), ''::text), ''::text) <> ''::text OR COALESCE(NULLIF(btrim(video_url), ''::text), ''::text) <> ''::text OR poll_id IS NOT NULL);
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_comment_count_check CHECK (comment_count >= 0);
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_like_count_check CHECK (like_count >= 0);
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_pkey PRIMARY KEY (id);
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_report_count_check CHECK (report_count >= 0);
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_repost_count_nonnegative CHECK (repost_count >= 0);
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_share_count_check CHECK (share_count >= 0);
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.feed_posts ADD CONSTRAINT feed_posts_view_count_check CHECK (view_count >= 0);
ALTER TABLE public.feed_preferences ADD CONSTRAINT feed_preferences_pkey PRIMARY KEY (user_id, post_id, preference);
ALTER TABLE public.feed_preferences ADD CONSTRAINT feed_preferences_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.feed_preferences ADD CONSTRAINT feed_preferences_preference_check CHECK (preference = ANY (ARRAY['not_interested'::text, 'hide_author'::text]));
ALTER TABLE public.feed_preferences ADD CONSTRAINT feed_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.follows ADD CONSTRAINT follows_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.follows ADD CONSTRAINT follows_following_id_fkey FOREIGN KEY (following_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.follows ADD CONSTRAINT follows_pkey PRIMARY KEY (follower_id, following_id);
ALTER TABLE public.follows ADD CONSTRAINT no_self_follow CHECK (follower_id <> following_id);
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_coins_awarded_check CHECK (coins_awarded >= 0);
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_pkey PRIMARY KEY (id);
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_question_id_fkey FOREIGN KEY (question_id) REFERENCES game_questions(id) ON DELETE RESTRICT;
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_response_ms_check CHECK (response_ms IS NULL OR response_ms >= 0 AND response_ms <= 120000);
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_round_id_fkey FOREIGN KEY (round_id) REFERENCES game_rounds(id) ON DELETE CASCADE;
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_score_awarded_check CHECK (score_awarded >= 0);
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_selected_index_check CHECK (selected_index >= '-1'::integer);
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.game_attempts ADD CONSTRAINT game_attempts_user_id_round_id_question_id_key UNIQUE (user_id, round_id, question_id);
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_challenged_id_fkey FOREIGN KEY (opponent_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_challenger_id_fkey FOREIGN KEY (challenger_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_challenger_score_check CHECK (challenger_score IS NULL OR challenger_score >= 0 AND challenger_score <= 500);
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_check CHECK (challenger_id <> opponent_id);
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_game_type_check CHECK (game_type = ANY (ARRAY['brain_mix'::text, 'math_sprint'::text, 'logic'::text, 'memory'::text, 'word_power'::text, 'general_knowledge'::text]));
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_opponent_score_check CHECK (opponent_score IS NULL OR opponent_score >= 0 AND opponent_score <= 500);
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_pkey PRIMARY KEY (id);
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_status_check CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text]));
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.game_challenges ADD CONSTRAINT game_challenges_winner_participant_check CHECK (winner_id IS NULL OR winner_id = challenger_id OR winner_id = opponent_id);
ALTER TABLE public.game_coin_ledger ADD CONSTRAINT game_coin_ledger_delta_check CHECK (delta <> 0);
ALTER TABLE public.game_coin_ledger ADD CONSTRAINT game_coin_ledger_pkey PRIMARY KEY (id);
ALTER TABLE public.game_coin_ledger ADD CONSTRAINT game_coin_ledger_question_id_fkey FOREIGN KEY (question_id) REFERENCES game_questions(id) ON DELETE SET NULL;
ALTER TABLE public.game_coin_ledger ADD CONSTRAINT game_coin_ledger_round_id_fkey FOREIGN KEY (round_id) REFERENCES game_rounds(id) ON DELETE SET NULL;
ALTER TABLE public.game_coin_ledger ADD CONSTRAINT game_coin_ledger_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.game_profiles ADD CONSTRAINT game_profiles_best_streak_check CHECK (best_streak >= 0);
ALTER TABLE public.game_profiles ADD CONSTRAINT game_profiles_coins_check CHECK (coins >= 0);
ALTER TABLE public.game_profiles ADD CONSTRAINT game_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.game_profiles ADD CONSTRAINT game_profiles_score_check CHECK (score >= 0);
ALTER TABLE public.game_profiles ADD CONSTRAINT game_profiles_streak_check CHECK (streak >= 0);
ALTER TABLE public.game_profiles ADD CONSTRAINT game_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.game_profiles ADD CONSTRAINT game_profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.game_question_reports ADD CONSTRAINT game_question_reports_details_check CHECK (char_length(details) <= 500);
ALTER TABLE public.game_question_reports ADD CONSTRAINT game_question_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.game_question_reports ADD CONSTRAINT game_question_reports_question_id_fkey FOREIGN KEY (question_id) REFERENCES game_questions(id) ON DELETE CASCADE;
ALTER TABLE public.game_question_reports ADD CONSTRAINT game_question_reports_reason_check CHECK (char_length(reason) >= 2 AND char_length(reason) <= 80);
ALTER TABLE public.game_question_reports ADD CONSTRAINT game_question_reports_status_check CHECK (status = ANY (ARRAY['open'::text, 'reviewing'::text, 'resolved'::text, 'dismissed'::text]));
ALTER TABLE public.game_question_reports ADD CONSTRAINT game_question_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.game_question_reports ADD CONSTRAINT game_question_reports_user_id_question_id_key UNIQUE (user_id, question_id);
ALTER TABLE public.game_questions ADD CONSTRAINT game_questions_check CHECK (correct_index < cardinality(options));
ALTER TABLE public.game_questions ADD CONSTRAINT game_questions_correct_index_check CHECK (correct_index >= 0);
ALTER TABLE public.game_questions ADD CONSTRAINT game_questions_difficulty_check CHECK (difficulty >= 1 AND difficulty <= 3);
ALTER TABLE public.game_questions ADD CONSTRAINT game_questions_game_type_check CHECK (game_type = ANY (ARRAY['brain_mix'::text, 'math_sprint'::text, 'logic'::text, 'memory'::text, 'word_power'::text, 'general_knowledge'::text]));
ALTER TABLE public.game_questions ADD CONSTRAINT game_questions_options_check CHECK (cardinality(options) >= 2 AND cardinality(options) <= 6);
ALTER TABLE public.game_questions ADD CONSTRAINT game_questions_pkey PRIMARY KEY (id);
ALTER TABLE public.game_questions ADD CONSTRAINT game_questions_time_limit_seconds_check CHECK (time_limit_seconds IS NULL OR time_limit_seconds >= 5 AND time_limit_seconds <= 120);
ALTER TABLE public.game_rewards ADD CONSTRAINT game_rewards_pkey PRIMARY KEY (id);
ALTER TABLE public.game_rewards ADD CONSTRAINT game_rewards_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES game_challenges(id) ON DELETE SET NULL;
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_coins_earned_check CHECK (coins_earned >= 0);
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_correct_count_check CHECK (correct_count >= 0);
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_game_type_check CHECK (game_type = ANY (ARRAY['brain_mix'::text, 'math_sprint'::text, 'logic'::text, 'memory'::text, 'word_power'::text, 'general_knowledge'::text]));
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_pkey PRIMARY KEY (id);
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_question_count_check CHECK (question_count >= 1 AND question_count <= 10);
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_score_check CHECK (score >= 0);
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_status_check CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'abandoned'::text, 'expired'::text]));
ALTER TABLE public.game_rounds ADD CONSTRAINT game_rounds_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.game_saved_questions ADD CONSTRAINT game_saved_questions_pkey PRIMARY KEY (user_id, question_id);
ALTER TABLE public.game_saved_questions ADD CONSTRAINT game_saved_questions_question_id_fkey FOREIGN KEY (question_id) REFERENCES game_questions(id) ON DELETE CASCADE;
ALTER TABLE public.game_saved_questions ADD CONSTRAINT game_saved_questions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.game_sessions ADD CONSTRAINT game_sessions_coins_earned_check CHECK (coins_earned >= 0);
ALTER TABLE public.game_sessions ADD CONSTRAINT game_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.game_sessions ADD CONSTRAINT game_sessions_round_id_fkey FOREIGN KEY (round_id) REFERENCES game_rounds(id) ON DELETE SET NULL;
ALTER TABLE public.game_sessions ADD CONSTRAINT game_sessions_score_check CHECK (score >= 0);
ALTER TABLE public.game_sessions ADD CONSTRAINT game_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.housing_agent_profiles ADD CONSTRAINT housing_agent_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.housing_agent_profiles ADD CONSTRAINT housing_agent_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.housing_agent_profiles ADD CONSTRAINT housing_agent_profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.housing_request_applications ADD CONSTRAINT housing_request_applications_agent_profile_id_fkey FOREIGN KEY (agent_profile_id) REFERENCES housing_agent_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.housing_request_applications ADD CONSTRAINT housing_request_applications_housing_request_id_fkey FOREIGN KEY (housing_request_id) REFERENCES housing_requests(id) ON DELETE CASCADE;
ALTER TABLE public.housing_request_applications ADD CONSTRAINT housing_request_applications_pkey PRIMARY KEY (id);
ALTER TABLE public.housing_request_applications ADD CONSTRAINT housing_request_applications_status_check CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'cancelled'::text]));
ALTER TABLE public.housing_requests ADD CONSTRAINT housing_requests_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES housing_agent_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.housing_requests ADD CONSTRAINT housing_requests_budget_max_check CHECK (budget_max IS NULL OR budget_max >= 0::numeric);
ALTER TABLE public.housing_requests ADD CONSTRAINT housing_requests_budget_min_check CHECK (budget_min IS NULL OR budget_min >= 0::numeric);
ALTER TABLE public.housing_requests ADD CONSTRAINT housing_requests_check CHECK (budget_min IS NULL OR budget_max IS NULL OR budget_max >= budget_min);
ALTER TABLE public.housing_requests ADD CONSTRAINT housing_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.housing_requests ADD CONSTRAINT housing_requests_status_check CHECK (status = ANY (ARRAY['open'::text, 'applied'::text, 'matched'::text, 'closed'::text, 'cancelled'::text]));
ALTER TABLE public.housing_requests ADD CONSTRAINT housing_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.interactions ADD CONSTRAINT interactions_pkey PRIMARY KEY (user_id, post_id, type);
ALTER TABLE public.interactions ADD CONSTRAINT interactions_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.interactions ADD CONSTRAINT interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.leaderboard_snapshots ADD CONSTRAINT leaderboard_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.leaderboard_snapshots ADD CONSTRAINT leaderboard_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.market_items ADD CONSTRAINT market_items_pkey PRIMARY KEY (id);
ALTER TABLE public.market_items ADD CONSTRAINT market_items_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_inquiries ADD CONSTRAINT marketplace_inquiries_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_inquiries ADD CONSTRAINT marketplace_inquiries_item_id_fkey FOREIGN KEY (item_id) REFERENCES market_items(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_inquiries ADD CONSTRAINT marketplace_inquiries_pkey PRIMARY KEY (id);
ALTER TABLE public.marketplace_inquiries ADD CONSTRAINT marketplace_inquiries_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_inquiries ADD CONSTRAINT marketplace_inquiries_status_check CHECK (status = ANY (ARRAY['pending'::text, 'responded'::text, 'closed'::text]));
ALTER TABLE public.marketplace_orders ADD CONSTRAINT marketplace_orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_orders ADD CONSTRAINT marketplace_orders_item_id_fkey FOREIGN KEY (item_id) REFERENCES market_items(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_orders ADD CONSTRAINT marketplace_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.marketplace_orders ADD CONSTRAINT marketplace_orders_quantity_check CHECK (quantity > 0);
ALTER TABLE public.marketplace_orders ADD CONSTRAINT marketplace_orders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_orders ADD CONSTRAINT marketplace_orders_status_check CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text, 'refunded'::text]));
ALTER TABLE public.marketplace_orders ADD CONSTRAINT marketplace_orders_total_price_check CHECK (total_price >= 0::numeric);
ALTER TABLE public.marketplace_orders ADD CONSTRAINT marketplace_orders_unit_price_check CHECK (unit_price >= 0::numeric);
ALTER TABLE public.marketplace_profiles ADD CONSTRAINT marketplace_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.marketplace_profiles ADD CONSTRAINT marketplace_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_profiles ADD CONSTRAINT marketplace_profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.marketplace_reviews ADD CONSTRAINT marketplace_reviews_check CHECK (reviewer_id <> reviewee_id);
ALTER TABLE public.marketplace_reviews ADD CONSTRAINT marketplace_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES marketplace_orders(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_reviews ADD CONSTRAINT marketplace_reviews_order_id_key UNIQUE (order_id);
ALTER TABLE public.marketplace_reviews ADD CONSTRAINT marketplace_reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.marketplace_reviews ADD CONSTRAINT marketplace_reviews_rating_check CHECK (rating >= 1 AND rating <= 5);
ALTER TABLE public.marketplace_reviews ADD CONSTRAINT marketplace_reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_reviews ADD CONSTRAINT marketplace_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_wishlist ADD CONSTRAINT marketplace_wishlist_item_id_fkey FOREIGN KEY (item_id) REFERENCES market_items(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_wishlist ADD CONSTRAINT marketplace_wishlist_pkey PRIMARY KEY (user_id, item_id);
ALTER TABLE public.marketplace_wishlist ADD CONSTRAINT marketplace_wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.mentor_profiles ADD CONSTRAINT mentor_profiles_mode_check CHECK (mode = ANY (ARRAY['mentor'::text, 'mentee'::text, 'both'::text]));
ALTER TABLE public.mentor_profiles ADD CONSTRAINT mentor_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.mentor_profiles ADD CONSTRAINT mentor_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.mentor_profiles ADD CONSTRAINT mentor_profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.mentor_requests ADD CONSTRAINT mentor_requests_mentor_profile_id_fkey FOREIGN KEY (mentor_profile_id) REFERENCES mentor_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.mentor_requests ADD CONSTRAINT mentor_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.mentor_requests ADD CONSTRAINT mentor_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.mentor_requests ADD CONSTRAINT mentor_requests_status_check CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'cancelled'::text]));
ALTER TABLE public.message_pins ADD CONSTRAINT message_pins_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.message_pins ADD CONSTRAINT message_pins_message_id_fkey FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_pins ADD CONSTRAINT message_pins_pinned_by_fkey FOREIGN KEY (pinned_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.message_pins ADD CONSTRAINT message_pins_pkey PRIMARY KEY (message_id);
ALTER TABLE public.message_push_dispatches ADD CONSTRAINT message_push_dispatches_attempts_check CHECK (attempts >= 1);
ALTER TABLE public.message_push_dispatches ADD CONSTRAINT message_push_dispatches_message_id_fkey FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_push_dispatches ADD CONSTRAINT message_push_dispatches_pkey PRIMARY KEY (message_id);
ALTER TABLE public.message_push_dispatches ADD CONSTRAINT message_push_dispatches_status_check CHECK (status = ANY (ARRAY['sending'::text, 'sent'::text, 'failed'::text]));
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_emoji_check CHECK (char_length(emoji) >= 1 AND char_length(emoji) <= 16);
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_message_id_fkey FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_pkey PRIMARY KEY (message_id, user_id, emoji);
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.message_reports ADD CONSTRAINT message_reports_message_id_fkey FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_reports ADD CONSTRAINT message_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.message_reports ADD CONSTRAINT message_reports_reason_check CHECK (char_length(reason) >= 1 AND char_length(reason) <= 500);
ALTER TABLE public.message_reports ADD CONSTRAINT message_reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.message_user_state ADD CONSTRAINT message_user_state_message_id_fkey FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_user_state ADD CONSTRAINT message_user_state_pkey PRIMARY KEY (message_id, user_id);
ALTER TABLE public.message_user_state ADD CONSTRAINT message_user_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.messages ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.messages ADD CONSTRAINT messages_pkey PRIMARY KEY (id);
ALTER TABLE public.messages ADD CONSTRAINT messages_reply_to_fkey FOREIGN KEY (reply_to) REFERENCES messages(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.messages_compat ADD CONSTRAINT messages_compat_pkey PRIMARY KEY (id);
ALTER TABLE public.muted_users ADD CONSTRAINT muted_users_check CHECK (user_id <> muted_id);
ALTER TABLE public.muted_users ADD CONSTRAINT muted_users_muted_id_fkey FOREIGN KEY (muted_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.muted_users ADD CONSTRAINT muted_users_pkey PRIMARY KEY (id);
ALTER TABLE public.muted_users ADD CONSTRAINT muted_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.muted_users ADD CONSTRAINT muted_users_user_id_muted_id_key UNIQUE (user_id, muted_id);
