-- Blink Supabase recovery snapshot: public constraints N-Z
ALTER TABLE public.notifications ADD CONSTRAINT notifications_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.point_transactions ADD CONSTRAINT point_transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.point_transactions ADD CONSTRAINT point_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.poll_options ADD CONSTRAINT poll_options_pkey PRIMARY KEY (id);
ALTER TABLE public.poll_options ADD CONSTRAINT poll_options_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE;
ALTER TABLE public.poll_options ADD CONSTRAINT poll_options_vote_count_check CHECK (vote_count >= 0);
ALTER TABLE public.poll_votes ADD CONSTRAINT poll_votes_option_id_fkey FOREIGN KEY (option_id) REFERENCES poll_options(id) ON DELETE CASCADE;
ALTER TABLE public.poll_votes ADD CONSTRAINT poll_votes_pkey PRIMARY KEY (id);
ALTER TABLE public.poll_votes ADD CONSTRAINT poll_votes_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE;
ALTER TABLE public.poll_votes ADD CONSTRAINT poll_votes_poll_id_user_id_key UNIQUE (poll_id, user_id);
ALTER TABLE public.poll_votes ADD CONSTRAINT poll_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.polls ADD CONSTRAINT polls_pkey PRIMARY KEY (id);
ALTER TABLE public.polls ADD CONSTRAINT polls_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.post_ads ADD CONSTRAINT post_ads_advertiser_id_fkey FOREIGN KEY (advertiser_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.post_ads ADD CONSTRAINT post_ads_budget_check CHECK (budget >= 0::numeric);
ALTER TABLE public.post_ads ADD CONSTRAINT post_ads_pkey PRIMARY KEY (id);
ALTER TABLE public.post_ads ADD CONSTRAINT post_ads_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.post_ads ADD CONSTRAINT post_ads_spent_check CHECK (spent >= 0::numeric);
ALTER TABLE public.post_ads ADD CONSTRAINT post_ads_status_check CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'paused'::text, 'completed'::text, 'rejected'::text]));
ALTER TABLE public.post_bookmarks ADD CONSTRAINT post_bookmarks_pkey PRIMARY KEY (id);
ALTER TABLE public.post_bookmarks ADD CONSTRAINT post_bookmarks_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.post_bookmarks ADD CONSTRAINT post_bookmarks_post_id_user_id_key UNIQUE (post_id, user_id);
ALTER TABLE public.post_bookmarks ADD CONSTRAINT post_bookmarks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.post_likes ADD CONSTRAINT post_likes_pkey PRIMARY KEY (id);
ALTER TABLE public.post_likes ADD CONSTRAINT post_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.post_likes ADD CONSTRAINT post_likes_post_id_user_id_key UNIQUE (post_id, user_id);
ALTER TABLE public.post_likes ADD CONSTRAINT post_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.post_reposts ADD CONSTRAINT post_reposts_pkey PRIMARY KEY (id);
ALTER TABLE public.post_reposts ADD CONSTRAINT post_reposts_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.post_reposts ADD CONSTRAINT post_reposts_post_id_user_id_key UNIQUE (post_id, user_id);
ALTER TABLE public.post_reposts ADD CONSTRAINT post_reposts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.post_shares ADD CONSTRAINT post_shares_pkey PRIMARY KEY (id);
ALTER TABLE public.post_shares ADD CONSTRAINT post_shares_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.post_shares ADD CONSTRAINT post_shares_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.post_views ADD CONSTRAINT post_views_impression_count_check CHECK (impression_count >= 1 AND impression_count <= 100);
ALTER TABLE public.post_views ADD CONSTRAINT post_views_pkey PRIMARY KEY (id);
ALTER TABLE public.post_views ADD CONSTRAINT post_views_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.post_views ADD CONSTRAINT post_views_weighted_view_count_check CHECK (weighted_view_count >= impression_count);
ALTER TABLE public.post_views ADD CONSTRAINT post_views_weighted_view_count_max_check CHECK (weighted_view_count <= 600);
ALTER TABLE public.profile_posts ADD CONSTRAINT profile_posts_pkey PRIMARY KEY (id);
ALTER TABLE public.profile_skills ADD CONSTRAINT profile_skills_pkey PRIMARY KEY (id);
ALTER TABLE public.profile_skills ADD CONSTRAINT profile_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE;
ALTER TABLE public.profile_skills ADD CONSTRAINT profile_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profile_skills ADD CONSTRAINT profile_skills_user_id_skill_id_key UNIQUE (user_id, skill_id);
ALTER TABLE public.profile_views ADD CONSTRAINT profile_views_pkey PRIMARY KEY (id);
ALTER TABLE public.profile_views ADD CONSTRAINT profile_views_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.profile_views ADD CONSTRAINT profile_views_viewer_id_fkey FOREIGN KEY (viewer_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_availability_check CHECK (availability = ANY (ARRAY['None'::text, 'Open for opportunities'::text, 'Available for freelance'::text, 'Looking for study buddy'::text, 'Busy / Exams'::text]));
ALTER TABLE public.profiles ADD CONSTRAINT profiles_current_wallet_balance_check CHECK (current_wallet_balance >= 0);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_follower_count_check CHECK (follower_count >= 0);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_following_count_check CHECK (following_count >= 0);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_posts_count_check CHECK (posts_count >= 0);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_profile_views_this_week_check CHECK (profile_views_this_week >= 0);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_username_key UNIQUE (username);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_verification_badge_check CHECK (verification_badge = ANY (ARRAY['NONE'::text, 'BLUE'::text, 'GOLD'::text]));
ALTER TABLE public.reading_mate_profiles ADD CONSTRAINT reading_mate_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.reading_mate_profiles ADD CONSTRAINT reading_mate_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.reading_mate_profiles ADD CONSTRAINT reading_mate_profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.reading_mate_requests ADD CONSTRAINT reading_mate_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.reading_mate_requests ADD CONSTRAINT reading_mate_requests_reading_profile_id_fkey FOREIGN KEY (reading_profile_id) REFERENCES reading_mate_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.reading_mate_requests ADD CONSTRAINT reading_mate_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.reading_mate_requests ADD CONSTRAINT reading_mate_requests_status_check CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'cancelled'::text]));
ALTER TABLE public.recommendation_events ADD CONSTRAINT recommendation_events_dwell_ms_check CHECK (dwell_ms >= 0 AND dwell_ms <= 600000);
ALTER TABLE public.recommendation_events ADD CONSTRAINT recommendation_events_event_type_check CHECK (event_type = ANY (ARRAY['impression'::text, 'open'::text, 'click'::text, 'dwell'::text, 'skip'::text, 'hide'::text, 'report'::text, 'purchase'::text, 'apply'::text, 'connect'::text, 'challenge'::text, 'complete'::text]));
ALTER TABLE public.recommendation_events ADD CONSTRAINT recommendation_events_metadata_check CHECK (jsonb_typeof(metadata) = 'object'::text);
ALTER TABLE public.recommendation_events ADD CONSTRAINT recommendation_events_pkey PRIMARY KEY (id);
ALTER TABLE public.recommendation_events ADD CONSTRAINT recommendation_events_surface_check CHECK (surface = ANY (ARRAY['feed'::text, 'reels'::text, 'market'::text, 'search'::text, 'connect'::text, 'game'::text]));
ALTER TABLE public.recommendation_events ADD CONSTRAINT recommendation_events_target_key_check CHECK (char_length(target_key) >= 1 AND char_length(target_key) <= 128);
ALTER TABLE public.recommendation_events ADD CONSTRAINT recommendation_events_target_type_check CHECK (target_type = ANY (ARRAY['post'::text, 'market_item'::text, 'profile'::text, 'connect_listing'::text, 'roommate'::text, 'mentor'::text, 'reading_mate'::text, 'housing'::text, 'game'::text]));
ALTER TABLE public.recommendation_events ADD CONSTRAINT recommendation_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.reports ADD CONSTRAINT reports_pkey PRIMARY KEY (id);
ALTER TABLE public.reports ADD CONSTRAINT reports_reported_comment_id_fkey FOREIGN KEY (reported_comment_id) REFERENCES comments(id) ON DELETE CASCADE;
ALTER TABLE public.reports ADD CONSTRAINT reports_reported_post_id_fkey FOREIGN KEY (reported_post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.reports ADD CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.repost_point_credits ADD CONSTRAINT repost_point_credits_action_type_check CHECK (action_type = ANY (ARRAY['repost'::text, 'view'::text, 'like'::text, 'comment'::text, 'save'::text, 'share'::text]));
ALTER TABLE public.repost_point_credits ADD CONSTRAINT repost_point_credits_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.repost_point_credits ADD CONSTRAINT repost_point_credits_pkey PRIMARY KEY (id);
ALTER TABLE public.repost_point_credits ADD CONSTRAINT repost_point_credits_points_each_check CHECK (points_each > 0);
ALTER TABLE public.repost_point_credits ADD CONSTRAINT repost_point_credits_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE CASCADE;
ALTER TABLE public.repost_point_credits ADD CONSTRAINT repost_point_credits_post_id_reposter_id_actor_id_action_ty_key UNIQUE (post_id, reposter_id, actor_id, action_type);
ALTER TABLE public.repost_point_credits ADD CONSTRAINT repost_point_credits_reposter_id_fkey FOREIGN KEY (reposter_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.roommate_applications ADD CONSTRAINT roommate_applications_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.roommate_applications ADD CONSTRAINT roommate_applications_pkey PRIMARY KEY (id);
ALTER TABLE public.roommate_applications ADD CONSTRAINT roommate_applications_roommate_profile_id_fkey FOREIGN KEY (roommate_profile_id) REFERENCES roommate_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.roommate_applications ADD CONSTRAINT roommate_applications_status_check CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'withdrawn'::text]));
ALTER TABLE public.roommate_profiles ADD CONSTRAINT roommate_profiles_budget_max_check CHECK (budget_max IS NULL OR budget_max >= 0::numeric);
ALTER TABLE public.roommate_profiles ADD CONSTRAINT roommate_profiles_budget_min_check CHECK (budget_min IS NULL OR budget_min >= 0::numeric);
ALTER TABLE public.roommate_profiles ADD CONSTRAINT roommate_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.roommate_profiles ADD CONSTRAINT roommate_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.scheduled_feed_posts ADD CONSTRAINT scheduled_feed_posts_payload_check CHECK (jsonb_typeof(payload) = 'object'::text);
ALTER TABLE public.scheduled_feed_posts ADD CONSTRAINT scheduled_feed_posts_pkey PRIMARY KEY (id);
ALTER TABLE public.scheduled_feed_posts ADD CONSTRAINT scheduled_feed_posts_published_post_id_fkey FOREIGN KEY (published_post_id) REFERENCES feed_posts(id) ON DELETE SET NULL;
ALTER TABLE public.scheduled_feed_posts ADD CONSTRAINT scheduled_feed_posts_status_check CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'published'::text, 'failed'::text, 'cancelled'::text]));
ALTER TABLE public.scheduled_feed_posts ADD CONSTRAINT scheduled_feed_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.skill_endorsements ADD CONSTRAINT skill_endorsements_check CHECK (profile_user_id <> endorser_user_id);
ALTER TABLE public.skill_endorsements ADD CONSTRAINT skill_endorsements_endorser_user_id_fkey FOREIGN KEY (endorser_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.skill_endorsements ADD CONSTRAINT skill_endorsements_pkey PRIMARY KEY (id);
ALTER TABLE public.skill_endorsements ADD CONSTRAINT skill_endorsements_profile_user_id_fkey FOREIGN KEY (profile_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.skill_endorsements ADD CONSTRAINT skill_endorsements_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE;
ALTER TABLE public.skill_endorsements ADD CONSTRAINT skill_endorsements_skill_id_profile_user_id_endorser_user_i_key UNIQUE (skill_id, profile_user_id, endorser_user_id);
ALTER TABLE public.skills ADD CONSTRAINT skills_normalized_name_key UNIQUE (normalized_name);
ALTER TABLE public.skills ADD CONSTRAINT skills_pkey PRIMARY KEY (id);
ALTER TABLE public.statuses ADD CONSTRAINT statuses_pkey PRIMARY KEY (id);
ALTER TABLE public.statuses ADD CONSTRAINT statuses_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.statuses ADD CONSTRAINT statuses_views_count_check CHECK (views_count >= 0);
ALTER TABLE public.stories ADD CONSTRAINT stories_pkey PRIMARY KEY (id);
ALTER TABLE public.stories ADD CONSTRAINT stories_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.story_interactions ADD CONSTRAINT story_interactions_pkey PRIMARY KEY (id);
ALTER TABLE public.story_interactions ADD CONSTRAINT story_interactions_status_id_fkey FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE;
ALTER TABLE public.story_interactions ADD CONSTRAINT story_interactions_status_id_user_id_type_key UNIQUE (status_id, user_id, type);
ALTER TABLE public.story_interactions ADD CONSTRAINT story_interactions_type_check CHECK (type = ANY (ARRAY['like'::text, 'reply'::text]));
ALTER TABLE public.story_interactions ADD CONSTRAINT story_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.story_likes ADD CONSTRAINT story_likes_pkey PRIMARY KEY (id);
ALTER TABLE public.story_likes ADD CONSTRAINT story_likes_story_id_fkey FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE;
ALTER TABLE public.story_likes ADD CONSTRAINT story_likes_story_id_user_id_key UNIQUE (story_id, user_id);
ALTER TABLE public.story_likes ADD CONSTRAINT story_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.story_reactions ADD CONSTRAINT story_reactions_pkey PRIMARY KEY (id);
ALTER TABLE public.story_reactions ADD CONSTRAINT story_reactions_story_id_fkey FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE;
ALTER TABLE public.story_reactions ADD CONSTRAINT story_reactions_story_id_user_id_key UNIQUE (story_id, user_id);
ALTER TABLE public.story_reactions ADD CONSTRAINT story_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.story_replies ADD CONSTRAINT story_replies_pkey PRIMARY KEY (id);
ALTER TABLE public.story_replies ADD CONSTRAINT story_replies_story_id_fkey FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE;
ALTER TABLE public.story_replies ADD CONSTRAINT story_replies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.story_views ADD CONSTRAINT story_views_pkey PRIMARY KEY (id);
ALTER TABLE public.story_views ADD CONSTRAINT story_views_story_id_fkey FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE;
ALTER TABLE public.story_views ADD CONSTRAINT story_views_story_id_user_id_key UNIQUE (story_id, user_id);
ALTER TABLE public.story_views ADD CONSTRAINT story_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.study_circle_members ADD CONSTRAINT study_circle_members_circle_id_fkey FOREIGN KEY (circle_id) REFERENCES study_circles(id) ON DELETE CASCADE;
ALTER TABLE public.study_circle_members ADD CONSTRAINT study_circle_members_pkey PRIMARY KEY (circle_id, user_id);
ALTER TABLE public.study_circle_members ADD CONSTRAINT study_circle_members_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text]));
ALTER TABLE public.study_circle_members ADD CONSTRAINT study_circle_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.study_circle_requests ADD CONSTRAINT study_circle_requests_circle_id_fkey FOREIGN KEY (circle_id) REFERENCES study_circles(id) ON DELETE CASCADE;
ALTER TABLE public.study_circle_requests ADD CONSTRAINT study_circle_requests_circle_id_user_id_key UNIQUE (circle_id, user_id);
ALTER TABLE public.study_circle_requests ADD CONSTRAINT study_circle_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.study_circle_requests ADD CONSTRAINT study_circle_requests_status_check CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'declined'::text]));
ALTER TABLE public.study_circle_requests ADD CONSTRAINT study_circle_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.study_circles ADD CONSTRAINT study_circles_max_members_check CHECK (max_members > 0);
ALTER TABLE public.study_circles ADD CONSTRAINT study_circles_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.study_circles ADD CONSTRAINT study_circles_pkey PRIMARY KEY (id);
ALTER TABLE public.token_transactions ADD CONSTRAINT token_transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.token_transactions ADD CONSTRAINT token_transactions_post_id_fkey FOREIGN KEY (post_id) REFERENCES feed_posts(id) ON DELETE SET NULL;
ALTER TABLE public.token_transactions ADD CONSTRAINT token_transactions_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.token_transactions ADD CONSTRAINT token_transactions_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.user_balances ADD CONSTRAINT user_balances_pkey PRIMARY KEY (user_id);
ALTER TABLE public.user_balances ADD CONSTRAINT user_balances_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.user_devices ADD CONSTRAINT user_devices_fcm_token_key UNIQUE (fcm_token);
ALTER TABLE public.user_devices ADD CONSTRAINT user_devices_pkey PRIMARY KEY (id);
ALTER TABLE public.user_interest_weights ADD CONSTRAINT user_interest_weights_feature_type_check CHECK (char_length(feature_type) >= 1 AND char_length(feature_type) <= 40);
ALTER TABLE public.user_interest_weights ADD CONSTRAINT user_interest_weights_feature_value_check CHECK (char_length(feature_value) >= 1 AND char_length(feature_value) <= 160);
ALTER TABLE public.user_interest_weights ADD CONSTRAINT user_interest_weights_pkey PRIMARY KEY (user_id, surface, feature_type, feature_value);
ALTER TABLE public.user_interest_weights ADD CONSTRAINT user_interest_weights_surface_check CHECK (surface = ANY (ARRAY['feed'::text, 'reels'::text, 'market'::text, 'search'::text, 'connect'::text, 'game'::text]));
ALTER TABLE public.user_interest_weights ADD CONSTRAINT user_interest_weights_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.user_interest_weights ADD CONSTRAINT user_interest_weights_weight_check CHECK (weight >= '-50'::integer::numeric AND weight <= 50::numeric);
ALTER TABLE public.user_settings ADD CONSTRAINT user_settings_pkey PRIMARY KEY (user_id);
ALTER TABLE public.verification_payments ADD CONSTRAINT verification_payments_amount_check CHECK (amount >= 0::numeric);
ALTER TABLE public.verification_payments ADD CONSTRAINT verification_payments_pkey PRIMARY KEY (id);
ALTER TABLE public.verification_payments ADD CONSTRAINT verification_payments_status_check CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text]));
ALTER TABLE public.verification_payments ADD CONSTRAINT verification_payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.verification_payments ADD CONSTRAINT verification_payments_verification_request_id_fkey FOREIGN KEY (verification_request_id) REFERENCES verification_requests(id) ON DELETE CASCADE;
ALTER TABLE public.verification_requests ADD CONSTRAINT verification_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.verification_requests ADD CONSTRAINT verification_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.verification_requests ADD CONSTRAINT verification_requests_status_check CHECK (status = ANY (ARRAY['pending'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text]));
ALTER TABLE public.verification_requests ADD CONSTRAINT verification_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.verifications ADD CONSTRAINT verifications_pkey PRIMARY KEY (id);
ALTER TABLE public.verifications ADD CONSTRAINT verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
