-- Blink Supabase recovery snapshot: public non-constraint indexes A-M
CREATE INDEX activities_recipient_idx ON public.activities USING btree (recipient_id, created_at DESC);
CREATE INDEX activities_unread_idx ON public.activities USING btree (recipient_id, is_read, created_at DESC);
CREATE INDEX idx_activities_actor_created ON public.activities USING btree (actor_id, created_at DESC);
CREATE INDEX idx_activities_actor_id ON public.activities USING btree (actor_id);
CREATE INDEX idx_activities_profile_view_dedupe ON public.activities USING btree (recipient_id, actor_id, entity_type, created_at DESC);
CREATE INDEX idx_activities_recipient_created ON public.activities USING btree (recipient_id, created_at DESC);
CREATE INDEX blink_boost_touches_viewer_idx ON public.blink_boost_touches USING btree (viewer_id);
CREATE INDEX blink_boosts_content_active_idx ON public.blink_boosts USING btree (content_id, ends_at) WHERE (status = 'ACTIVE'::text);
CREATE INDEX blink_boosts_inventory_idx ON public.blink_boosts USING btree (inventory_id);
CREATE INDEX blink_boosts_user_idx ON public.blink_boosts USING btree (user_id, created_at DESC);
CREATE INDEX blink_coin_gifts_receiver_created_idx ON public.blink_coin_gifts USING btree (receiver_id, created_at DESC);
CREATE INDEX blink_coin_gifts_sender_created_idx ON public.blink_coin_gifts USING btree (sender_id, created_at DESC);
CREATE INDEX blink_coin_transactions_catalog_idx ON public.blink_coin_transactions USING btree (catalog_id);
CREATE INDEX blink_coin_transactions_user_idx ON public.blink_coin_transactions USING btree (user_id, created_at DESC);
CREATE INDEX blink_digital_gifts_inventory_idx ON public.blink_digital_gifts USING btree (inventory_id);
CREATE INDEX blink_digital_gifts_recipient_idx ON public.blink_digital_gifts USING btree (recipient_id, created_at DESC);
CREATE INDEX blink_digital_gifts_sender_idx ON public.blink_digital_gifts USING btree (sender_id, created_at DESC);
CREATE INDEX blink_equipped_items_catalog_idx ON public.blink_equipped_items USING btree (catalog_id);
CREATE INDEX blink_equipped_items_inventory_idx ON public.blink_equipped_items USING btree (inventory_id);
CREATE INDEX blink_inventory_catalog_idx ON public.blink_inventory USING btree (catalog_id);
CREATE INDEX blink_inventory_gifted_by_idx ON public.blink_inventory USING btree (gifted_by);
CREATE INDEX blink_inventory_user_catalog_idx ON public.blink_inventory USING btree (user_id, catalog_id);
CREATE INDEX blink_inventory_user_status_idx ON public.blink_inventory USING btree (user_id, status, purchased_at DESC);
CREATE INDEX blink_item_activations_catalog_idx ON public.blink_item_activations USING btree (catalog_id);
CREATE INDEX blink_item_activations_inventory_idx ON public.blink_item_activations USING btree (inventory_id);
CREATE INDEX blink_item_activations_target_idx ON public.blink_item_activations USING btree (target_type, target_id, expires_at);
CREATE INDEX blink_item_activations_user_idx ON public.blink_item_activations USING btree (user_id, started_at DESC);
CREATE INDEX blink_vip_benefit_balances_user_idx ON public.blink_vip_benefit_balances USING btree (user_id);
CREATE INDEX blink_vip_claims_pass_idx ON public.blink_vip_claims USING btree (pass_id);
CREATE UNIQUE INDEX blink_vip_daily_claim_unique ON public.blink_vip_claims USING btree (user_id, claim_key, claim_date) WHERE (claim_date IS NOT NULL);
CREATE INDEX blink_vip_passes_gifted_by_idx ON public.blink_vip_passes USING btree (gifted_by);
CREATE INDEX blink_vip_passes_inventory_idx ON public.blink_vip_passes USING btree (inventory_id);
CREATE INDEX blink_vip_passes_user_expiry_idx ON public.blink_vip_passes USING btree (user_id, expires_at DESC);
CREATE INDEX call_signals_call_id_idx ON public.call_signals USING btree (call_id, id);
CREATE INDEX calls_callee_status_idx ON public.calls USING btree (callee_id, status, created_at DESC);
CREATE INDEX calls_caller_status_idx ON public.calls USING btree (caller_id, status, created_at DESC);
CREATE INDEX calls_conversation_created_idx ON public.calls USING btree (conversation_id, created_at DESC);
CREATE INDEX calls_timeout_idx ON public.calls USING btree (timeout_at) WHERE (status = 'ringing'::text);
CREATE INDEX comment_likes_comment_idx ON public.comment_likes USING btree (comment_id);
CREATE INDEX idx_comment_likes_user ON public.comment_likes USING btree (user_id);
CREATE INDEX comment_mentions_recipient_created_idx ON public.comment_mentions USING btree (mentioned_user_id, created_at DESC);
CREATE INDEX idx_comment_replies_author_id ON public.comment_replies USING btree (author_id);
CREATE INDEX idx_comment_replies_comment_id ON public.comment_replies USING btree (comment_id);
CREATE INDEX comments_author_idx ON public.comments USING btree (author_id);
CREATE INDEX comments_parent_idx ON public.comments USING btree (parent_comment_id);
CREATE INDEX comments_post_idx ON public.comments USING btree (post_id, created_at DESC);
CREATE INDEX connect_applications_applicant_idx ON public.connect_applications USING btree (applicant_id, updated_at DESC);
CREATE INDEX connect_applications_listing_idx ON public.connect_applications USING btree (listing_id, status, updated_at DESC);
CREATE INDEX connect_listings_discovery_idx ON public.connect_listings USING btree (listing_type, is_active, updated_at DESC);
CREATE UNIQUE INDEX connect_listings_one_active_type_per_user ON public.connect_listings USING btree (user_id, listing_type) WHERE is_active;
CREATE INDEX connect_listings_user_idx ON public.connect_listings USING btree (user_id, updated_at DESC);
CREATE INDEX ranking_connect_search_fts_idx ON public.connect_listings USING gin (to_tsvector('simple'::regconfig, ((((((((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(university, ''::text)) || ' '::text) || COALESCE(department, ''::text)) || ' '::text) || COALESCE(location, ''::text))));
CREATE INDEX ranking_connect_subjects_gin_idx ON public.connect_listings USING gin (subjects);
CREATE INDEX ranking_connect_tags_gin_idx ON public.connect_listings USING gin (tags);
CREATE INDEX connect_match_spins_pair_created_idx ON public.connect_match_spins USING btree (user_id, matched_user_id, created_at DESC);
CREATE INDEX connect_match_spins_user_created_idx ON public.connect_match_spins USING btree (user_id, created_at DESC);
CREATE INDEX connection_receiver_status_idx ON public.connection_requests USING btree (receiver_id, status);
CREATE INDEX connection_sender_status_idx ON public.connection_requests USING btree (sender_id, status);
CREATE INDEX idx_conn_req_receiver ON public.connection_requests USING btree (receiver_id);
CREATE INDEX idx_conn_req_sender ON public.connection_requests USING btree (sender_id);
CREATE INDEX idx_conn_req_status ON public.connection_requests USING btree (status);
CREATE UNIQUE INDEX uniq_active_connection_request ON public.connection_requests USING btree (LEAST(sender_id, receiver_id), GREATEST(sender_id, receiver_id)) WHERE (status = 'pending'::text);
CREATE INDEX conversation_participants_user_conversation_idx ON public.conversation_participants USING btree (user_id, conversation_id);
CREATE INDEX idx_conversation_participants_user ON public.conversation_participants USING btree (user_id, conversation_id);
CREATE INDEX idx_conversation_participants_user_id ON public.conversation_participants USING btree (user_id);
CREATE INDEX conversation_reports_conversation_idx ON public.conversation_reports USING btree (conversation_id);
CREATE INDEX conversation_reports_reporter_idx ON public.conversation_reports USING btree (reporter_id);
CREATE INDEX conversation_user_state_user_idx ON public.conversation_user_state USING btree (user_id);
CREATE INDEX conversations_created_by_idx ON public.conversations USING btree (created_by);
CREATE INDEX idx_conv_last_msg ON public.conversations USING btree (last_message_at DESC);
CREATE INDEX fcm_tokens_active_user_updated_idx ON public.fcm_tokens USING btree (user_id, updated_at DESC) WHERE (is_active = true);
CREATE UNIQUE INDEX fcm_tokens_token_uidx ON public.fcm_tokens USING btree (token);
CREATE INDEX fcm_tokens_user_updated_idx ON public.fcm_tokens USING btree (user_id, updated_at DESC);
CREATE INDEX discovery_feed_recent_idx ON public.feed_posts USING btree (created_at DESC, id DESC) INCLUDE (user_id, is_reel, like_count, comment_count, share_count, view_count, creator_post_number) WHERE ((is_active = true) AND (is_flagged = false) AND (is_sponsored = false));
CREATE INDEX feed_posts_category_idx ON public.feed_posts USING btree (category);
CREATE INDEX feed_posts_created_idx ON public.feed_posts USING btree (created_at DESC);
CREATE INDEX feed_posts_expiry_idx ON public.feed_posts USING btree (expires_at);
CREATE INDEX feed_posts_faculty_idx ON public.feed_posts USING btree (faculty);
CREATE INDEX feed_posts_page_idx ON public.feed_posts USING btree (created_at DESC, id DESC) WHERE (is_active = true);
CREATE INDEX feed_posts_reel_idx ON public.feed_posts USING btree (is_reel) WHERE (is_reel = true);
CREATE INDEX feed_posts_user_created_idx ON public.feed_posts USING btree (user_id, created_at DESC);
CREATE INDEX feed_posts_user_page_idx ON public.feed_posts USING btree (user_id, created_at DESC, id DESC) WHERE (is_active = true);
CREATE INDEX feed_posts_user_post_number_idx ON public.feed_posts USING btree (user_id, creator_post_number);
CREATE INDEX idx_feed_posts_created_active ON public.feed_posts USING btree (is_active, created_at DESC);
CREATE INDEX idx_feed_posts_created_at_desc ON public.feed_posts USING btree (created_at DESC);
CREATE INDEX idx_feed_posts_reels ON public.feed_posts USING btree (is_reel, created_at DESC) WHERE (is_active = true);
CREATE INDEX idx_feed_posts_search_text ON public.feed_posts USING gin (to_tsvector('simple'::regconfig, ((COALESCE(text, ''::text) || ' '::text) || COALESCE(caption, ''::text))));
CREATE INDEX idx_feed_posts_sponsored ON public.feed_posts USING btree (is_sponsored, created_at DESC);
CREATE INDEX ranking_feed_candidate_idx ON public.feed_posts USING btree (is_reel, created_at DESC, id DESC) WHERE ((is_active = true) AND (is_flagged = false));
CREATE INDEX ranking_feed_hashtags_gin_idx ON public.feed_posts USING gin (hashtags);
CREATE INDEX ranking_feed_search_fts_idx ON public.feed_posts USING gin (to_tsvector('simple'::regconfig, ((((((COALESCE(text, ''::text) || ' '::text) || COALESCE(caption, ''::text)) || ' '::text) || COALESCE(category, ''::text)) || ' '::text) || COALESCE(faculty, ''::text))));
CREATE INDEX ranking_feed_tags_gin_idx ON public.feed_posts USING gin (tags);
CREATE INDEX discovery_feed_preferences_user_post_idx ON public.feed_preferences USING btree (user_id, post_id, preference);
CREATE INDEX feed_preferences_user_created_idx ON public.feed_preferences USING btree (user_id, created_at DESC);
CREATE INDEX follows_follower_idx ON public.follows USING btree (follower_id);
CREATE INDEX follows_following_idx ON public.follows USING btree (following_id);
CREATE INDEX idx_follows_follower_following ON public.follows USING btree (follower_id, following_id);
CREATE INDEX game_attempts_question_user_idx ON public.game_attempts USING btree (question_id, user_id, created_at DESC);
CREATE INDEX game_attempts_round_idx ON public.game_attempts USING btree (round_id);
CREATE INDEX game_attempts_user_created_idx ON public.game_attempts USING btree (user_id, created_at DESC);
CREATE INDEX game_challenges_challenged_idx ON public.game_challenges USING btree (opponent_id, created_at DESC);
CREATE INDEX game_challenges_challenger_idx ON public.game_challenges USING btree (challenger_id, created_at DESC);
CREATE UNIQUE INDEX game_challenges_one_open_pair_type ON public.game_challenges USING btree (LEAST(challenger_id, opponent_id), GREATEST(challenger_id, opponent_id), game_type) WHERE (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'in_progress'::text]));
CREATE INDEX game_challenges_opponent_idx ON public.game_challenges USING btree (opponent_id, updated_at DESC);
CREATE UNIQUE INDEX game_challenges_pending_uidx ON public.game_challenges USING btree (LEAST(challenger_id, opponent_id), GREATEST(challenger_id, opponent_id), game_type) WHERE (status = ANY (ARRAY['pending'::text, 'accepted'::text]));
CREATE INDEX game_challenges_winner_idx ON public.game_challenges USING btree (winner_id);
CREATE INDEX game_coin_ledger_question_idx ON public.game_coin_ledger USING btree (question_id);
CREATE INDEX game_coin_ledger_round_idx ON public.game_coin_ledger USING btree (round_id);
CREATE INDEX game_coin_ledger_user_created_idx ON public.game_coin_ledger USING btree (user_id, created_at DESC);
CREATE INDEX game_question_reports_question_idx ON public.game_question_reports USING btree (question_id);
CREATE INDEX game_questions_daily_idx ON public.game_questions USING btree (is_daily, is_active) WHERE (is_daily = true);
CREATE INDEX game_questions_type_active_idx ON public.game_questions USING btree (game_type, is_active, difficulty);
CREATE INDEX idx_game_rewards_user ON public.game_rewards USING btree (user_id);
CREATE INDEX idx_game_rewards_user_created ON public.game_rewards USING btree (user_id, created_at DESC);
CREATE INDEX game_rounds_challenge_idx ON public.game_rounds USING btree (challenge_id) WHERE (challenge_id IS NOT NULL);
CREATE INDEX game_rounds_user_active_idx ON public.game_rounds USING btree (user_id, status, started_at DESC);
CREATE INDEX game_rounds_user_completed_idx ON public.game_rounds USING btree (user_id, completed_at DESC) WHERE (status = 'completed'::text);
CREATE INDEX game_saved_questions_question_idx ON public.game_saved_questions USING btree (question_id);
CREATE UNIQUE INDEX game_sessions_round_uidx ON public.game_sessions USING btree (round_id) WHERE (round_id IS NOT NULL);
CREATE INDEX game_sessions_user_idx ON public.game_sessions USING btree (user_id, started_at DESC);
CREATE INDEX idx_game_sessions_user ON public.game_sessions USING btree (user_id);
CREATE INDEX idx_game_sessions_user_started ON public.game_sessions USING btree (user_id, started_at DESC);
CREATE INDEX housing_agent_profiles_active_idx ON public.housing_agent_profiles USING btree (is_active, is_verified, created_at DESC);
CREATE INDEX housing_request_applications_agent_idx ON public.housing_request_applications USING btree (agent_profile_id, created_at DESC);
CREATE UNIQUE INDEX housing_request_applications_pending_uidx ON public.housing_request_applications USING btree (housing_request_id, agent_profile_id) WHERE (status = 'pending'::text);
CREATE INDEX housing_request_applications_request_idx ON public.housing_request_applications USING btree (housing_request_id, created_at DESC);
CREATE INDEX housing_requests_agent_idx ON public.housing_requests USING btree (agent_id, created_at DESC);
CREATE INDEX housing_requests_status_idx ON public.housing_requests USING btree (status, created_at DESC);
CREATE INDEX housing_requests_student_idx ON public.housing_requests USING btree (student_id, created_at DESC);
CREATE INDEX interactions_post_id_idx ON public.interactions USING btree (post_id);
CREATE INDEX leaderboard_snapshots_user_id_idx ON public.leaderboard_snapshots USING btree (user_id);
CREATE INDEX market_items_category_idx ON public.market_items USING btree (category);
CREATE INDEX market_items_seller_idx ON public.market_items USING btree (seller_id);
CREATE INDEX market_items_status_idx ON public.market_items USING btree (status);
CREATE INDEX ranking_market_candidate_idx ON public.market_items USING btree (category, created_at DESC, id DESC) WHERE ((status = 'active'::text) AND (is_sold = false));
CREATE INDEX ranking_market_search_fts_idx ON public.market_items USING gin (to_tsvector('simple'::regconfig, ((((((((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(category, ''::text)) || ' '::text) || COALESCE(location, ''::text)) || ' '::text) || COALESCE(university, ''::text))));
CREATE INDEX idx_mp_inq_buyer ON public.marketplace_inquiries USING btree (buyer_id);
CREATE INDEX idx_mp_inq_item ON public.marketplace_inquiries USING btree (item_id);
CREATE INDEX idx_mp_inq_seller ON public.marketplace_inquiries USING btree (seller_id);
CREATE INDEX idx_mp_order_buyer ON public.marketplace_orders USING btree (buyer_id);
CREATE INDEX idx_mp_order_item ON public.marketplace_orders USING btree (item_id);
CREATE INDEX idx_mp_order_seller ON public.marketplace_orders USING btree (seller_id);
CREATE INDEX idx_mp_order_status ON public.marketplace_orders USING btree (status);
CREATE INDEX marketplace_reviews_reviewee_idx ON public.marketplace_reviews USING btree (reviewee_id, created_at DESC);
CREATE INDEX mentor_profiles_active_idx ON public.mentor_profiles USING btree (is_active, created_at DESC);
CREATE UNIQUE INDEX mentor_requests_pending_uidx ON public.mentor_requests USING btree (mentor_profile_id, requester_id) WHERE (status = 'pending'::text);
CREATE INDEX mentor_requests_requester_idx ON public.mentor_requests USING btree (requester_id, created_at DESC);
CREATE INDEX message_pins_conversation_idx ON public.message_pins USING btree (conversation_id);
CREATE INDEX message_pins_pinned_by_idx ON public.message_pins USING btree (pinned_by);
CREATE INDEX message_reactions_user_idx ON public.message_reactions USING btree (user_id);
CREATE INDEX message_reports_message_idx ON public.message_reports USING btree (message_id);
CREATE INDEX message_reports_reporter_idx ON public.message_reports USING btree (reporter_id);
CREATE INDEX message_user_state_user_idx ON public.message_user_state USING btree (user_id);
CREATE INDEX idx_messages_conversation_created ON public.messages USING btree (conversation_id, created_at DESC);
CREATE INDEX idx_messages_conversation_receipts ON public.messages USING btree (conversation_id, sender_id, created_at DESC) INCLUDE (delivered_at, read_at, is_read);
CREATE INDEX messages_conversation_page_idx ON public.messages USING btree (conversation_id, created_at DESC, id DESC);
CREATE INDEX messages_reply_to_idx ON public.messages USING btree (reply_to);
CREATE INDEX messages_sender_idx ON public.messages USING btree (sender_id);
CREATE INDEX idx_muted_target ON public.muted_users USING btree (muted_id);
CREATE INDEX idx_muted_user ON public.muted_users USING btree (user_id);
