-- Blink Supabase recovery snapshot: public non-constraint indexes N-Z
CREATE INDEX idx_notifications_unread ON public.notifications USING btree (user_id, is_read, created_at DESC);
CREATE INDEX idx_notifications_user_created ON public.notifications USING btree (user_id, created_at DESC);
CREATE INDEX notifications_actor_id_idx ON public.notifications USING btree (actor_id);
CREATE INDEX notifications_post_id_idx ON public.notifications USING btree (post_id);
CREATE INDEX idx_point_transactions_created_at ON public.point_transactions USING btree (created_at DESC);
CREATE INDEX idx_point_transactions_user_id ON public.point_transactions USING btree (user_id);
CREATE UNIQUE INDEX uq_point_transactions_user_action_reference ON public.point_transactions USING btree (user_id, action_type, reference_id) WHERE (reference_id IS NOT NULL);
CREATE INDEX idx_poll_options_poll ON public.poll_options USING btree (poll_id);
CREATE INDEX idx_poll_votes_option ON public.poll_votes USING btree (option_id);
CREATE INDEX idx_poll_votes_poll ON public.poll_votes USING btree (poll_id);
CREATE INDEX poll_votes_user_id_idx ON public.poll_votes USING btree (user_id);
CREATE UNIQUE INDEX uniq_poll_vote ON public.poll_votes USING btree (poll_id, user_id, option_id);
CREATE INDEX idx_polls_post_id ON public.polls USING btree (post_id);
CREATE INDEX idx_post_ads_active ON public.post_ads USING btree (status, starts_at, ends_at);
CREATE INDEX idx_post_ads_advertiser_id ON public.post_ads USING btree (advertiser_id);
CREATE INDEX idx_post_ads_post_id ON public.post_ads USING btree (post_id);
CREATE INDEX idx_bookmarks_post ON public.post_bookmarks USING btree (post_id);
CREATE INDEX idx_bookmarks_user ON public.post_bookmarks USING btree (user_id);
CREATE INDEX post_bookmarks_user_idx ON public.post_bookmarks USING btree (user_id, created_at DESC);
CREATE INDEX post_likes_post_idx ON public.post_likes USING btree (post_id);
CREATE INDEX post_likes_user_idx ON public.post_likes USING btree (user_id);
CREATE INDEX post_reposts_post_created_idx ON public.post_reposts USING btree (post_id, created_at DESC);
CREATE INDEX post_reposts_user_created_idx ON public.post_reposts USING btree (user_id, created_at DESC);
CREATE INDEX idx_post_shares_post_id ON public.post_shares USING btree (post_id);
CREATE INDEX idx_shares_post ON public.post_shares USING btree (post_id);
CREATE INDEX idx_shares_user ON public.post_shares USING btree (user_id);
CREATE INDEX idx_post_views_created_at ON public.post_views USING btree (created_at DESC);
CREATE INDEX idx_post_views_post_created ON public.post_views USING btree (post_id, created_at DESC);
CREATE INDEX idx_post_views_post_id ON public.post_views USING btree (post_id);
CREATE INDEX idx_post_views_viewer_id ON public.post_views USING btree (viewer_id);
CREATE UNIQUE INDEX uniq_post_view ON public.post_views USING btree (post_id, viewer_id);
CREATE INDEX profile_posts_created_at_idx ON public.profile_posts USING btree (created_at DESC);
CREATE INDEX idx_profile_skills_user ON public.profile_skills USING btree (user_id);
CREATE INDEX profile_skills_skill_id_idx ON public.profile_skills USING btree (skill_id);
CREATE INDEX idx_profile_views_created_at ON public.profile_views USING btree (created_at DESC);
CREATE INDEX idx_profile_views_profile_id ON public.profile_views USING btree (profile_id);
CREATE INDEX idx_profile_views_profile_viewer_created ON public.profile_views USING btree (profile_id, viewer_id, created_at DESC);
CREATE INDEX idx_profile_views_viewer_id ON public.profile_views USING btree (viewer_id);
CREATE INDEX profile_views_profile_idx ON public.profile_views USING btree (profile_id, created_at DESC);
CREATE INDEX idx_profiles_points_desc ON public.profiles USING btree (points DESC, created_at);
CREATE INDEX idx_profiles_search_name ON public.profiles USING btree (lower(full_name));
CREATE INDEX idx_profiles_search_username ON public.profiles USING btree (lower(username));
CREATE INDEX idx_profiles_username_lower ON public.profiles USING btree (lower(username)) WHERE ((username IS NOT NULL) AND (TRIM(BOTH FROM username) <> ''::text));
CREATE INDEX profiles_course_idx ON public.profiles USING btree (course_of_study);
CREATE INDEX profiles_department_idx ON public.profiles USING btree (department);
CREATE INDEX profiles_faculty_idx ON public.profiles USING btree (faculty);
CREATE UNIQUE INDEX profiles_full_name_ci_unique ON public.profiles USING btree (lower(btrim(full_name))) WHERE ((btrim(full_name) <> ''::text) AND (lower(btrim(full_name)) <> 'blink user'::text) AND (NULLIF(btrim(username), ''::text) IS NOT NULL));
CREATE INDEX profiles_full_name_trgm_idx ON public.profiles USING gin (lower(full_name) gin_trgm_ops);
CREATE INDEX profiles_name_trgm_idx ON public.profiles USING gin (full_name gin_trgm_ops);
CREATE INDEX profiles_university_idx ON public.profiles USING btree (university);
CREATE UNIQUE INDEX profiles_username_ci_unique ON public.profiles USING btree (lower(btrim(username))) WHERE (NULLIF(btrim(username), ''::text) IS NOT NULL);
CREATE UNIQUE INDEX profiles_username_normalized_uidx ON public.profiles USING btree (lower(TRIM(BOTH FROM username))) WHERE (TRIM(BOTH FROM username) <> ''::text);
CREATE INDEX profiles_username_trgm_idx ON public.profiles USING gin (username gin_trgm_ops);
CREATE INDEX ranking_profiles_hobbies_gin_idx ON public.profiles USING gin (hobbies);
CREATE INDEX ranking_profiles_search_fts_idx ON public.profiles USING gin (to_tsvector('simple'::regconfig, ((((((((((((COALESCE(username, ''::text) || ' '::text) || COALESCE(full_name, ''::text)) || ' '::text) || COALESCE(name, ''::text)) || ' '::text) || COALESCE(university, ''::text)) || ' '::text) || COALESCE(faculty, ''::text)) || ' '::text) || COALESCE(department, ''::text)) || ' '::text) || COALESCE(bio, ''::text))));
CREATE INDEX ranking_profiles_skills_gin_idx ON public.profiles USING gin (core_skills);
CREATE INDEX reading_mate_profiles_active_idx ON public.reading_mate_profiles USING btree (is_active, created_at DESC);
CREATE UNIQUE INDEX reading_mate_requests_pending_uidx ON public.reading_mate_requests USING btree (reading_profile_id, requester_id) WHERE (status = 'pending'::text);
CREATE INDEX reading_mate_requests_requester_idx ON public.reading_mate_requests USING btree (requester_id, created_at DESC);
CREATE INDEX recommendation_events_created_brin_idx ON public.recommendation_events USING brin (created_at);
CREATE INDEX recommendation_events_user_surface_created_idx ON public.recommendation_events USING btree (user_id, surface, created_at DESC);
CREATE INDEX recommendation_events_user_target_idx ON public.recommendation_events USING btree (user_id, target_type, target_key, created_at DESC);
CREATE INDEX idx_reports_reported_post_id ON public.reports USING btree (reported_post_id);
CREATE INDEX idx_reports_reported_user_id ON public.reports USING btree (reported_user_id);
CREATE UNIQUE INDEX reports_one_pending_comment_per_user_idx ON public.reports USING btree (reporter_id, reported_comment_id) WHERE ((reported_comment_id IS NOT NULL) AND (COALESCE(status, 'pending'::text) = 'pending'::text));
CREATE INDEX reports_reported_comment_id_idx ON public.reports USING btree (reported_comment_id);
CREATE INDEX repost_point_credits_actor_idx ON public.repost_point_credits USING btree (actor_id, created_at DESC);
CREATE INDEX repost_point_credits_post_idx ON public.repost_point_credits USING btree (post_id, created_at DESC);
CREATE INDEX repost_point_credits_reposter_idx ON public.repost_point_credits USING btree (reposter_id, created_at DESC);
CREATE INDEX idx_roommate_app_applicant ON public.roommate_applications USING btree (applicant_id);
CREATE INDEX idx_roommate_app_profile ON public.roommate_applications USING btree (roommate_profile_id);
CREATE INDEX idx_roommate_active ON public.roommate_profiles USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_roommate_user ON public.roommate_profiles USING btree (user_id);
CREATE INDEX roommate_profiles_active_idx ON public.roommate_profiles USING btree (is_active, created_at DESC);
CREATE UNIQUE INDEX roommate_profiles_user_id_uidx ON public.roommate_profiles USING btree (user_id);
CREATE INDEX scheduled_feed_posts_due_idx ON public.scheduled_feed_posts USING btree (status, scheduled_for) WHERE (status = 'pending'::text);
CREATE INDEX scheduled_feed_posts_user_idx ON public.scheduled_feed_posts USING btree (user_id, created_at DESC);
CREATE INDEX idx_skill_endorsements_profile ON public.skill_endorsements USING btree (profile_user_id);
CREATE INDEX skill_endorsements_endorser_user_id_idx ON public.skill_endorsements USING btree (endorser_user_id);
CREATE INDEX statuses_user_id_idx ON public.statuses USING btree (user_id);
CREATE INDEX idx_stories_user_id ON public.stories USING btree (user_id);
CREATE INDEX stories_active_created_at_idx ON public.stories USING btree (active, created_at DESC);
CREATE INDEX story_interactions_user_id_idx ON public.story_interactions USING btree (user_id);
CREATE INDEX idx_story_likes_story ON public.story_likes USING btree (story_id);
CREATE INDEX story_likes_user_id_idx ON public.story_likes USING btree (user_id);
CREATE INDEX idx_story_reactions_story ON public.story_reactions USING btree (story_id);
CREATE INDEX story_reactions_user_id_idx ON public.story_reactions USING btree (user_id);
CREATE INDEX idx_story_replies_story ON public.story_replies USING btree (story_id);
CREATE INDEX story_replies_user_id_idx ON public.story_replies USING btree (user_id);
CREATE INDEX idx_story_views_story ON public.story_views USING btree (story_id);
CREATE INDEX story_views_user_id_idx ON public.story_views USING btree (user_id);
CREATE INDEX idx_circle_members_user ON public.study_circle_members USING btree (user_id);
CREATE INDEX study_circle_members_user_idx ON public.study_circle_members USING btree (user_id, joined_at DESC);
CREATE INDEX idx_circle_requests_circle ON public.study_circle_requests USING btree (circle_id);
CREATE INDEX study_circle_requests_circle_status_idx ON public.study_circle_requests USING btree (circle_id, status, created_at DESC);
CREATE INDEX study_circle_requests_user_id_idx ON public.study_circle_requests USING btree (user_id);
CREATE INDEX study_circle_requests_user_idx ON public.study_circle_requests USING btree (user_id, created_at DESC);
CREATE INDEX idx_circle_owner ON public.study_circles USING btree (owner_id);
CREATE INDEX token_transactions_post_id_idx ON public.token_transactions USING btree (post_id);
CREATE INDEX token_transactions_recipient_id_idx ON public.token_transactions USING btree (recipient_id);
CREATE INDEX token_transactions_sender_id_idx ON public.token_transactions USING btree (sender_id);
CREATE INDEX discovery_interest_weights_lookup_idx ON public.user_interest_weights USING btree (user_id, surface, feature_type, weight DESC, updated_at DESC);
CREATE INDEX user_interest_weights_lookup_idx ON public.user_interest_weights USING btree (user_id, surface, feature_type, weight DESC);
CREATE INDEX idx_verif_pay_request ON public.verification_payments USING btree (verification_request_id);
CREATE INDEX idx_verif_pay_user ON public.verification_payments USING btree (user_id);
CREATE INDEX idx_verif_status ON public.verification_requests USING btree (status);
CREATE INDEX idx_verif_user ON public.verification_requests USING btree (user_id);
CREATE UNIQUE INDEX verification_requests_one_open_per_type ON public.verification_requests USING btree (user_id, upper(verification_type)) WHERE (status = ANY (ARRAY['pending'::text, 'under_review'::text]));
CREATE INDEX verification_requests_reviewed_by_idx ON public.verification_requests USING btree (reviewed_by);
CREATE INDEX verification_requests_user_idx ON public.verification_requests USING btree (user_id, submitted_at DESC);
CREATE INDEX verifications_user_id_idx ON public.verifications USING btree (user_id);
