-- Blink Supabase recovery snapshot: all custom app triggers plus Blink triggers on auth.users.
-- Trigger functions are captured separately in the function snapshot/migrations.

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();
CREATE TRIGGER trg_admin_guard_auth_registration BEFORE INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION private.guard_registration_admin_controls();
CREATE TRIGGER trg_normalize_admin_campaign_message BEFORE INSERT OR UPDATE OF title, message, subtopic ON private.admin_notification_campaigns FOR EACH ROW EXECUTE FUNCTION private.normalize_admin_campaign_message();
CREATE TRIGGER protect_blink_owner_role BEFORE DELETE OR UPDATE ON private.admin_roles FOR EACH ROW EXECUTE FUNCTION private.protect_blink_owner_role();
CREATE TRIGGER trg_admin_guard_coin_gifts BEFORE INSERT ON public.blink_coin_gifts FOR EACH ROW EXECUTE FUNCTION private.guard_coin_transfer_admin_controls();
CREATE TRIGGER trg_sync_comment_like_count AFTER INSERT OR DELETE ON public.comment_likes FOR EACH ROW EXECUTE FUNCTION public.sync_comment_like_count();
CREATE TRIGGER trg_activity_comment_mention AFTER INSERT ON public.comment_mentions FOR EACH ROW EXECUTE FUNCTION public.activity_from_comment_mention();
CREATE TRIGGER ranking_learn_comments AFTER INSERT OR DELETE ON public.comments FOR EACH ROW EXECUTE FUNCTION private_ranking.capture_native_signal();
CREATE TRIGGER trg_activity_post_comment AFTER INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION public.activity_from_post_comment();
CREATE TRIGGER trg_admin_guard_comments BEFORE INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION private.guard_comment_admin_controls();
CREATE TRIGGER trg_points_comment AFTER INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION public.award_interaction_points();
CREATE TRIGGER trg_repost_credit_comment AFTER INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION public.award_repost_points_from_interaction();
CREATE TRIGGER trg_sync_comment_mentions AFTER INSERT OR UPDATE OF content ON public.comments FOR EACH ROW EXECUTE FUNCTION public.sync_comment_mentions();
CREATE TRIGGER trg_sync_post_comment_count AFTER INSERT OR DELETE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.sync_post_comment_count();
CREATE TRIGGER trg_validate_comment_write BEFORE INSERT OR UPDATE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.validate_comment_write();
CREATE TRIGGER connect_applications_guard BEFORE UPDATE ON public.connect_applications FOR EACH ROW EXECUTE FUNCTION public.guard_connect_application_update();
CREATE TRIGGER connect_applications_updated_at BEFORE UPDATE ON public.connect_applications FOR EACH ROW EXECUTE FUNCTION public.set_connect_updated_at();
CREATE TRIGGER connect_listings_updated_at BEFORE UPDATE ON public.connect_listings FOR EACH ROW EXECUTE FUNCTION public.set_connect_updated_at();
CREATE TRIGGER trg_activity_connection_request AFTER INSERT ON public.connection_requests FOR EACH ROW EXECUTE FUNCTION public.activity_from_connection();
CREATE TRIGGER enforce_blink_owner_post BEFORE INSERT OR UPDATE ON public.feed_posts FOR EACH ROW EXECUTE FUNCTION private.enforce_blink_owner_post();
CREATE TRIGGER guard_feed_post_view_count_insert BEFORE INSERT ON public.feed_posts FOR EACH ROW EXECUTE FUNCTION private.guard_feed_post_view_count();
CREATE TRIGGER guard_feed_post_view_count_update BEFORE UPDATE OF view_count ON public.feed_posts FOR EACH ROW EXECUTE FUNCTION private.guard_feed_post_view_count();
CREATE TRIGGER trg_admin_guard_feed_posts BEFORE INSERT ON public.feed_posts FOR EACH ROW EXECUTE FUNCTION private.guard_feed_post_admin_controls();
CREATE TRIGGER trg_assign_creator_post_number BEFORE INSERT ON public.feed_posts FOR EACH ROW EXECUTE FUNCTION private_ranking.assign_creator_post_number();
CREATE TRIGGER trg_normalize_feed_post_media BEFORE INSERT OR UPDATE ON public.feed_posts FOR EACH ROW EXECUTE FUNCTION public.normalize_feed_post_media();
CREATE TRIGGER trg_points_create_post AFTER INSERT ON public.feed_posts FOR EACH ROW EXECUTE FUNCTION public.award_interaction_points();
CREATE TRIGGER trg_admin_guard_follows BEFORE INSERT ON public.follows FOR EACH ROW EXECUTE FUNCTION private.guard_follow_admin_controls();
CREATE TRIGGER trg_notify_follow_created AFTER INSERT ON public.follows FOR EACH ROW EXECUTE FUNCTION public.notify_follow_created();
CREATE TRIGGER trg_points_follow AFTER INSERT ON public.follows FOR EACH ROW EXECUTE FUNCTION public.award_interaction_points();
CREATE TRIGGER trg_sync_follow_counts AFTER INSERT OR DELETE ON public.follows FOR EACH ROW EXECUTE FUNCTION public.sync_follow_counts();
CREATE TRIGGER trg_sync_profile_follow_counts AFTER INSERT OR DELETE ON public.follows FOR EACH ROW EXECUTE FUNCTION public.sync_profile_follow_counts();
CREATE TRIGGER trg_track_blink_boost_follow AFTER INSERT ON public.follows FOR EACH ROW EXECUTE FUNCTION private.track_blink_boost_follow();
CREATE TRIGGER game_challenges_updated_at BEFORE UPDATE ON public.game_challenges FOR EACH ROW EXECUTE FUNCTION public.set_connect_updated_at();
CREATE TRIGGER ranking_learn_game_sessions AFTER INSERT OR DELETE ON public.game_sessions FOR EACH ROW EXECUTE FUNCTION private_ranking.capture_native_signal();
CREATE TRIGGER trg_prevent_agent_self_verification BEFORE INSERT OR UPDATE ON public.housing_agent_profiles FOR EACH ROW EXECUTE FUNCTION public.prevent_agent_self_verification();
CREATE TRIGGER trg_protect_housing_application_updates BEFORE UPDATE ON public.housing_request_applications FOR EACH ROW EXECUTE FUNCTION public.protect_housing_application_updates();
CREATE TRIGGER trg_protect_housing_request_updates BEFORE UPDATE ON public.housing_requests FOR EACH ROW EXECUTE FUNCTION public.protect_connect_hub_request_updates();
CREATE TRIGGER trg_admin_guard_market_items BEFORE INSERT ON public.market_items FOR EACH ROW EXECUTE FUNCTION private.guard_market_admin_controls();
CREATE TRIGGER trg_guard_marketplace_verified_seller BEFORE INSERT OR UPDATE ON public.marketplace_profiles FOR EACH ROW EXECUTE FUNCTION public.guard_marketplace_verified_seller();
CREATE TRIGGER ranking_learn_market_wishlist AFTER INSERT OR DELETE ON public.marketplace_wishlist FOR EACH ROW EXECUTE FUNCTION private_ranking.capture_native_signal();
CREATE TRIGGER trg_protect_mentor_request_updates BEFORE UPDATE ON public.mentor_requests FOR EACH ROW EXECUTE FUNCTION public.protect_connect_hub_request_updates();
CREATE TRIGGER trg_admin_guard_messages BEFORE INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION private.guard_message_admin_controls();
CREATE TRIGGER trg_dispatch_message_push_after_insert AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.dispatch_message_push_after_insert();
CREATE TRIGGER trg_notify_message_created AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.notify_message_created();
CREATE TRIGGER trg_points_message AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.award_message_points();
CREATE TRIGGER trg_update_conv_last_msg AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.update_conversation_last_message();
CREATE TRIGGER trg_decorate_blink_notification BEFORE INSERT OR UPDATE OF actor_id, type ON public.notifications FOR EACH ROW EXECUTE FUNCTION private.decorate_blink_notification();
CREATE TRIGGER trg_track_admin_notification_open AFTER UPDATE OF is_read ON public.notifications FOR EACH ROW EXECUTE FUNCTION private.track_admin_notification_open();
CREATE TRIGGER trg_recalc_poll_option_vote_count AFTER INSERT OR DELETE ON public.poll_votes FOR EACH ROW EXECUTE FUNCTION public.recalc_poll_option_vote_count();
CREATE TRIGGER trg_admin_guard_post_ads BEFORE INSERT OR UPDATE ON public.post_ads FOR EACH ROW EXECUTE FUNCTION private.guard_post_ads_admin_controls();
CREATE TRIGGER ranking_learn_bookmarks AFTER INSERT OR DELETE ON public.post_bookmarks FOR EACH ROW EXECUTE FUNCTION private_ranking.capture_native_signal();
CREATE TRIGGER trg_activity_post_bookmark AFTER INSERT ON public.post_bookmarks FOR EACH ROW EXECUTE FUNCTION public.activity_from_bookmark();
CREATE TRIGGER trg_points_post_bookmark AFTER INSERT ON public.post_bookmarks FOR EACH ROW EXECUTE FUNCTION public.award_save_points();
CREATE TRIGGER trg_repost_credit_bookmark AFTER INSERT ON public.post_bookmarks FOR EACH ROW EXECUTE FUNCTION public.award_repost_points_from_interaction();
CREATE TRIGGER ranking_learn_post_likes AFTER INSERT OR DELETE ON public.post_likes FOR EACH ROW EXECUTE FUNCTION private_ranking.capture_native_signal();
CREATE TRIGGER trg_activity_post_like AFTER INSERT ON public.post_likes FOR EACH ROW EXECUTE FUNCTION public.activity_from_post_like();
CREATE TRIGGER trg_points_post_like AFTER INSERT ON public.post_likes FOR EACH ROW EXECUTE FUNCTION public.award_interaction_points();
CREATE TRIGGER trg_post_like_count AFTER INSERT OR DELETE ON public.post_likes FOR EACH ROW EXECUTE FUNCTION public.update_post_like_count();
CREATE TRIGGER trg_repost_credit_post_like AFTER INSERT ON public.post_likes FOR EACH ROW EXECUTE FUNCTION public.award_repost_points_from_interaction();
CREATE TRIGGER trg_repost_credit_create AFTER INSERT ON public.post_reposts FOR EACH ROW EXECUTE FUNCTION public.award_repost_points_on_create();
CREATE TRIGGER trg_sync_post_repost_count_delete AFTER DELETE ON public.post_reposts FOR EACH ROW EXECUTE FUNCTION public.sync_post_repost_count();
CREATE TRIGGER trg_sync_post_repost_count_insert AFTER INSERT ON public.post_reposts FOR EACH ROW EXECUTE FUNCTION public.sync_post_repost_count();
CREATE TRIGGER ranking_learn_shares AFTER INSERT OR DELETE ON public.post_shares FOR EACH ROW EXECUTE FUNCTION private_ranking.capture_native_signal();
CREATE TRIGGER trg_points_post_share AFTER INSERT ON public.post_shares FOR EACH ROW EXECUTE FUNCTION public.award_share_points();
CREATE TRIGGER trg_repost_credit_share AFTER INSERT ON public.post_shares FOR EACH ROW EXECUTE FUNCTION public.award_repost_points_from_interaction();
CREATE TRIGGER trg_track_blink_boost_view AFTER INSERT OR UPDATE OF impression_count ON public.post_views FOR EACH ROW EXECUTE FUNCTION private.track_blink_boost_view();
CREATE TRIGGER trg_track_blink_boost_profile_visit AFTER INSERT ON public.profile_views FOR EACH ROW EXECUTE FUNCTION private.track_blink_boost_profile_visit();
CREATE TRIGGER normalize_profile_identity_trigger BEFORE INSERT OR UPDATE OF username, full_name ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.normalize_profile_identity();
CREATE TRIGGER trg_ensure_profile_username BEFORE INSERT OR UPDATE OF username, email ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.ensure_profile_username();
CREATE TRIGGER trg_guard_profile_daily_streak BEFORE UPDATE OF daily_streak ON public.profiles FOR EACH ROW EXECUTE FUNCTION private.guard_profile_daily_streak();
CREATE TRIGGER trg_guard_profile_privileged_fields BEFORE INSERT OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.guard_profile_privileged_fields();
CREATE TRIGGER trg_normalize_profile_username BEFORE INSERT OR UPDATE OF username ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.normalize_profile_username();
CREATE TRIGGER trg_profiles_ensure_user_balance AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION private.ensure_user_balance_row();
CREATE TRIGGER trg_protect_blink_owner_verification BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION private.protect_blink_owner_verification();
CREATE TRIGGER trg_protect_reading_request_updates BEFORE UPDATE ON public.reading_mate_requests FOR EACH ROW EXECUTE FUNCTION public.protect_connect_hub_request_updates();
CREATE TRIGGER recommendation_events_learn_trigger AFTER INSERT ON public.recommendation_events FOR EACH ROW EXECUTE FUNCTION private_ranking.capture_recommendation_event();
CREATE TRIGGER trg_protect_roommate_application_updates BEFORE UPDATE ON public.roommate_applications FOR EACH ROW EXECUTE FUNCTION public.protect_roommate_application_updates();
CREATE TRIGGER trg_recalc_story_like_count AFTER INSERT OR DELETE ON public.story_likes FOR EACH ROW EXECUTE FUNCTION public.recalc_story_like_count();
CREATE TRIGGER trg_sync_story_like_count AFTER INSERT OR DELETE ON public.story_likes FOR EACH ROW EXECUTE FUNCTION public.sync_story_like_count();
CREATE TRIGGER trg_recalc_story_view_count AFTER INSERT OR DELETE ON public.story_views FOR EACH ROW EXECUTE FUNCTION public.recalc_story_view_count();
CREATE TRIGGER trg_story_view_count AFTER INSERT ON public.story_views FOR EACH ROW EXECUTE FUNCTION public.update_story_view_count();
CREATE TRIGGER trg_admin_guard_token_transactions BEFORE INSERT ON public.token_transactions FOR EACH ROW EXECUTE FUNCTION private.guard_coin_transfer_admin_controls();
CREATE TRIGGER trg_admin_guard_verification_requests BEFORE INSERT ON public.verification_requests FOR EACH ROW EXECUTE FUNCTION private.guard_verification_requests_admin_controls();
