-- Blinkng professional calling foundations: privacy, participants, quality telemetry,
-- recovery diagnostics, retry metadata and scheduled stale-state cleanup.
-- destructive-change-reviewed
-- rollback-plan: Drop only the newly added telemetry/event tables and columns; remove the cron job and restore the prior start_call definition. No user messages or call-history rows are deleted by rollback.

alter table public.calls
  add column if not exists is_group_call boolean not null default false,
  add column if not exists reconnect_count integer not null default 0,
  add column if not exists setup_latency_ms integer,
  add column if not exists last_quality_score numeric(5,2),
  add column if not exists network_type text,
  add column if not exists turn_used boolean not null default false,
  add column if not exists ended_cleanly boolean not null default false,
  add column if not exists client_call_id uuid;

create unique index if not exists calls_caller_client_call_uidx
  on public.calls(caller_id, client_call_id)
  where client_call_id is not null;

alter table public.call_signals
  add column if not exists sequence_no bigint,
  add column if not exists device_id text;

create sequence if not exists public.call_signal_server_sequence_seq;

create or replace function private.assign_call_signal_server_sequence()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.sequence_no is null then
    new.sequence_no := nextval('public.call_signal_server_sequence_seq'::regclass);
  end if;
  return new;
end;
$$;

revoke all on function private.assign_call_signal_server_sequence() from public, anon, authenticated;
drop trigger if exists trg_assign_call_signal_server_sequence on public.call_signals;
create trigger trg_assign_call_signal_server_sequence
before insert on public.call_signals
for each row execute function private.assign_call_signal_server_sequence();

create table if not exists public.call_participants (
  call_id uuid not null references public.calls(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'participant' check (role in ('host','cohost','participant')),
  state text not null default 'invited' check (state in ('invited','ringing','joining','connected','held','left','declined','failed')),
  microphone_enabled boolean not null default true,
  camera_enabled boolean not null default false,
  screen_sharing boolean not null default false,
  hand_raised boolean not null default false,
  joined_at timestamptz,
  left_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (call_id, user_id)
);

create index if not exists call_participants_user_state_idx on public.call_participants(user_id, state, updated_at desc);
alter table public.call_participants enable row level security;
drop policy if exists "call_participants_participant_select" on public.call_participants;
create policy "call_participants_participant_select" on public.call_participants
for select to authenticated
using (
  exists (
    select 1 from public.call_participants mine
    where mine.call_id = call_participants.call_id
      and mine.user_id = (select auth.uid())
  )
  or exists (
    select 1 from public.calls c
    where c.id = call_participants.call_id
      and (c.caller_id = (select auth.uid()) or c.callee_id = (select auth.uid()))
  )
);
drop policy if exists "call_participants_self_update" on public.call_participants;
create policy "call_participants_self_update" on public.call_participants
for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));
revoke all on public.call_participants from anon;
grant select, update on public.call_participants to authenticated;

create table if not exists public.call_events (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.calls(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists call_events_call_id_idx on public.call_events(call_id, id desc);
alter table public.call_events enable row level security;
drop policy if exists "call_events_participant_select" on public.call_events;
create policy "call_events_participant_select" on public.call_events
for select to authenticated
using (
  exists (
    select 1 from public.calls c
    where c.id = call_events.call_id
      and (c.caller_id = (select auth.uid()) or c.callee_id = (select auth.uid()))
  ) or exists (
    select 1 from public.call_participants cp
    where cp.call_id = call_events.call_id and cp.user_id = (select auth.uid())
  )
);
revoke all on public.call_events from anon, authenticated;
grant select on public.call_events to authenticated;

create table if not exists public.call_quality_samples (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.calls(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id text,
  sampled_at timestamptz not null default now(),
  connection_state text,
  network_type text,
  round_trip_ms numeric(10,2),
  jitter_ms numeric(10,2),
  packets_lost bigint,
  packets_received bigint,
  audio_bitrate_bps bigint,
  video_bitrate_bps bigint,
  frames_per_second numeric(8,2),
  frame_width integer,
  frame_height integer,
  frames_dropped bigint,
  local_candidate_type text,
  remote_candidate_type text,
  turn_used boolean not null default false,
  quality_score numeric(5,2),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists call_quality_samples_call_time_idx on public.call_quality_samples(call_id, sampled_at desc);
create index if not exists call_quality_samples_user_time_idx on public.call_quality_samples(user_id, sampled_at desc);
alter table public.call_quality_samples enable row level security;
drop policy if exists "call_quality_samples_participant_select" on public.call_quality_samples;
create policy "call_quality_samples_participant_select" on public.call_quality_samples
for select to authenticated
using (
  exists (
    select 1 from public.calls c
    where c.id = call_quality_samples.call_id
      and (c.caller_id = (select auth.uid()) or c.callee_id = (select auth.uid()))
  ) or exists (
    select 1 from public.call_participants cp
    where cp.call_id = call_quality_samples.call_id and cp.user_id = (select auth.uid())
  )
);
drop policy if exists "call_quality_samples_self_insert" on public.call_quality_samples;
create policy "call_quality_samples_self_insert" on public.call_quality_samples
for insert to authenticated
with check (
  user_id = (select auth.uid()) and (
    exists (
      select 1 from public.calls c
      where c.id = call_quality_samples.call_id
        and (c.caller_id = (select auth.uid()) or c.callee_id = (select auth.uid()))
    ) or exists (
      select 1 from public.call_participants cp
      where cp.call_id = call_quality_samples.call_id and cp.user_id = (select auth.uid())
    )
  )
);
revoke all on public.call_quality_samples from anon;
grant select, insert on public.call_quality_samples to authenticated;

create table if not exists public.call_network_events (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.calls(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id text,
  event_type text not null check (event_type in ('network_changed','ice_restart','reconnecting','reconnected','turn_fallback','audio_route_changed','backgrounded','foregrounded','media_interrupted','media_resumed')),
  from_value text,
  to_value text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists call_network_events_call_idx on public.call_network_events(call_id, id desc);
alter table public.call_network_events enable row level security;
drop policy if exists "call_network_events_participant_select" on public.call_network_events;
create policy "call_network_events_participant_select" on public.call_network_events
for select to authenticated
using (
  exists (
    select 1 from public.calls c
    where c.id = call_network_events.call_id
      and (c.caller_id = (select auth.uid()) or c.callee_id = (select auth.uid()))
  ) or exists (
    select 1 from public.call_participants cp
    where cp.call_id = call_network_events.call_id and cp.user_id = (select auth.uid())
  )
);
drop policy if exists "call_network_events_self_insert" on public.call_network_events;
create policy "call_network_events_self_insert" on public.call_network_events
for insert to authenticated
with check (user_id = (select auth.uid()));
revoke all on public.call_network_events from anon;
grant select, insert on public.call_network_events to authenticated;

alter table public.call_push_dispatches
  add column if not exists next_attempt_at timestamptz,
  add column if not exists dead_letter_at timestamptz,
  add column if not exists response_code integer,
  add column if not exists first_attempt_at timestamptz not null default now();

alter table public.message_push_dispatches
  add column if not exists next_attempt_at timestamptz,
  add column if not exists dead_letter_at timestamptz,
  add column if not exists response_code integer,
  add column if not exists first_attempt_at timestamptz not null default now();

create index if not exists call_push_dispatch_retry_idx
  on public.call_push_dispatches(next_attempt_at)
  where status = 'failed' and dead_letter_at is null;
create index if not exists message_push_dispatch_retry_idx
  on public.message_push_dispatches(next_attempt_at)
  where status = 'failed' and dead_letter_at is null;

create or replace function private.sync_initial_call_participants()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.call_participants(call_id,user_id,role,state,camera_enabled,updated_at)
  values
    (new.id,new.caller_id,'host','connected',new.call_type='video',now()),
    (new.id,new.callee_id,'participant','ringing',new.call_type='video',now())
  on conflict (call_id,user_id) do nothing;
  return new;
end;
$$;

revoke all on function private.sync_initial_call_participants() from public, anon, authenticated;
drop trigger if exists trg_sync_initial_call_participants on public.calls;
create trigger trg_sync_initial_call_participants
after insert on public.calls
for each row execute function private.sync_initial_call_participants();

create or replace function private.record_call_status_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.call_events(call_id,actor_id,event_type,metadata)
    values (new.id,new.caller_id,'ringing',jsonb_build_object('call_type',new.call_type));
  elsif new.status is distinct from old.status then
    insert into public.call_events(call_id,actor_id,event_type,metadata)
    values (
      new.id,
      coalesce(new.ended_by, auth.uid()),
      new.status,
      jsonb_build_object('previous_status',old.status,'end_reason',new.end_reason)
    );
  end if;
  return new;
end;
$$;

revoke all on function private.record_call_status_event() from public, anon, authenticated;
drop trigger if exists trg_record_call_status_event on public.calls;
create trigger trg_record_call_status_event
after insert or update on public.calls
for each row execute function private.record_call_status_event();

create or replace function public.start_call(
  p_conversation_id uuid,
  p_callee_id uuid,
  p_call_type text
)
returns public.calls
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_caller_id uuid := auth.uid();
  v_call public.calls;
begin
  if v_caller_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  if p_callee_id is null or p_callee_id = v_caller_id then raise exception 'INVALID_CALLEE'; end if;
  if p_call_type not in ('audio','video') then raise exception 'INVALID_CALL_TYPE'; end if;
  if not exists (
    select 1 from public.conversation_participants cp
    where cp.conversation_id=p_conversation_id and cp.user_id=v_caller_id and cp.left_at is null and cp.can_call=true
  ) or not exists (
    select 1 from public.conversation_participants cp
    where cp.conversation_id=p_conversation_id and cp.user_id=p_callee_id and cp.left_at is null and cp.can_call=true
  ) then raise exception 'NOT_CONVERSATION_PARTICIPANT'; end if;
  if not private.chat_scope_allows(v_caller_id,p_callee_id,'call') then raise exception 'CALL_PRIVACY_BLOCKED'; end if;

  update public.calls
     set status='missed',ended_at=now(),end_reason='timeout',ended_cleanly=true
   where status='ringing' and timeout_at<=now()
     and (caller_id in (v_caller_id,p_callee_id) or callee_id in (v_caller_id,p_callee_id));

  if exists (
    select 1 from public.calls c
    where c.status in ('ringing','connecting','connected')
      and (c.caller_id in (v_caller_id,p_callee_id) or c.callee_id in (v_caller_id,p_callee_id))
  ) then raise exception 'USER_BUSY'; end if;

  insert into public.calls(conversation_id,caller_id,callee_id,call_type)
  values (p_conversation_id,v_caller_id,p_callee_id,p_call_type)
  returning * into v_call;
  return v_call;
end;
$$;

create or replace function public.start_call_v2(
  p_conversation_id uuid,
  p_callee_id uuid,
  p_call_type text,
  p_client_call_id uuid
)
returns public.calls
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
  v_existing public.calls;
  v_created public.calls;
begin
  if v_me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  if p_client_call_id is null then raise exception 'CLIENT_CALL_ID_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_me::text || ':call:' || p_client_call_id::text,0));
  select * into v_existing from public.calls
  where caller_id=v_me and client_call_id=p_client_call_id limit 1;
  if found then return v_existing; end if;
  v_created := public.start_call(p_conversation_id,p_callee_id,p_call_type);
  update public.calls set client_call_id=p_client_call_id where id=v_created.id returning * into v_created;
  return v_created;
end;
$$;

create or replace function public.invite_call_participant(p_call_id uuid,p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
  v_call public.calls;
begin
  if v_me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  select * into v_call from public.calls where id=p_call_id for update;
  if not found then raise exception 'CALL_NOT_FOUND'; end if;
  if v_call.caller_id <> v_me then raise exception 'CALL_HOST_REQUIRED'; end if;
  if v_call.status not in ('ringing','connecting','connected') then raise exception 'CALL_NOT_ACTIVE'; end if;
  if not exists (
    select 1 from public.conversation_participants cp
    where cp.conversation_id=v_call.conversation_id and cp.user_id=p_user_id and cp.left_at is null and cp.can_call=true
  ) then raise exception 'NOT_CONVERSATION_PARTICIPANT'; end if;
  if not private.chat_scope_allows(v_me,p_user_id,'call') then raise exception 'CALL_PRIVACY_BLOCKED'; end if;

  insert into public.call_participants(call_id,user_id,role,state,camera_enabled,updated_at)
  values (p_call_id,p_user_id,'participant','invited',v_call.call_type='video',now())
  on conflict (call_id,user_id) do update set state='invited',left_at=null,updated_at=now();
  update public.calls set is_group_call=true where id=p_call_id;
  insert into public.call_events(call_id,actor_id,event_type,metadata)
  values (p_call_id,v_me,'participant_invited',jsonb_build_object('target_user_id',p_user_id));
  return true;
end;
$$;

create or replace function public.record_call_quality_sample(
  p_call_id uuid,
  p_device_id text,
  p_connection_state text,
  p_network_type text,
  p_round_trip_ms numeric,
  p_jitter_ms numeric,
  p_packets_lost bigint,
  p_packets_received bigint,
  p_audio_bitrate_bps bigint,
  p_video_bitrate_bps bigint,
  p_frames_per_second numeric,
  p_frame_width integer,
  p_frame_height integer,
  p_frames_dropped bigint,
  p_local_candidate_type text,
  p_remote_candidate_type text,
  p_turn_used boolean,
  p_quality_score numeric,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = 'public','pg_temp'
as $$
declare
  v_me uuid := auth.uid();
  v_id bigint;
begin
  if v_me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  if not exists (
    select 1 from public.calls c
    where c.id=p_call_id and (c.caller_id=v_me or c.callee_id=v_me)
  ) and not exists (
    select 1 from public.call_participants cp where cp.call_id=p_call_id and cp.user_id=v_me
  ) then raise exception 'CALL_NOT_ACCESSIBLE'; end if;

  insert into public.call_quality_samples(
    call_id,user_id,device_id,connection_state,network_type,round_trip_ms,jitter_ms,
    packets_lost,packets_received,audio_bitrate_bps,video_bitrate_bps,frames_per_second,
    frame_width,frame_height,frames_dropped,local_candidate_type,remote_candidate_type,
    turn_used,quality_score,metadata
  ) values (
    p_call_id,v_me,nullif(left(coalesce(p_device_id,''),200),''),p_connection_state,p_network_type,
    greatest(coalesce(p_round_trip_ms,0),0),greatest(coalesce(p_jitter_ms,0),0),
    greatest(coalesce(p_packets_lost,0),0),greatest(coalesce(p_packets_received,0),0),
    greatest(coalesce(p_audio_bitrate_bps,0),0),greatest(coalesce(p_video_bitrate_bps,0),0),
    greatest(coalesce(p_frames_per_second,0),0),p_frame_width,p_frame_height,
    greatest(coalesce(p_frames_dropped,0),0),p_local_candidate_type,p_remote_candidate_type,
    coalesce(p_turn_used,false),greatest(0,least(coalesce(p_quality_score,0),100)),coalesce(p_metadata,'{}'::jsonb)
  ) returning id into v_id;

  update public.calls
     set last_quality_score=greatest(0,least(coalesce(p_quality_score,last_quality_score,0),100)),
         network_type=coalesce(nullif(p_network_type,''),network_type),
         turn_used=turn_used or coalesce(p_turn_used,false)
   where id=p_call_id;
  return v_id;
end;
$$;

create or replace function public.record_call_network_event(
  p_call_id uuid,
  p_device_id text,
  p_event_type text,
  p_from_value text default null,
  p_to_value text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = 'public','pg_temp'
as $$
declare
  v_me uuid := auth.uid();
  v_id bigint;
begin
  if v_me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  insert into public.call_network_events(call_id,user_id,device_id,event_type,from_value,to_value,metadata)
  values (p_call_id,v_me,nullif(left(coalesce(p_device_id,''),200),''),p_event_type,p_from_value,p_to_value,coalesce(p_metadata,'{}'::jsonb))
  returning id into v_id;
  if p_event_type='ice_restart' then update public.calls set reconnect_count=reconnect_count+1 where id=p_call_id; end if;
  return v_id;
end;
$$;

create or replace function public.get_call_quality_summary(p_call_id uuid)
returns table(
  sample_count bigint,
  avg_round_trip_ms numeric,
  avg_jitter_ms numeric,
  avg_quality_score numeric,
  total_packets_lost numeric,
  turn_sample_count bigint,
  reconnect_count integer
)
language plpgsql
security invoker
set search_path = 'public','pg_temp'
stable
as $$
declare
  v_me uuid := auth.uid();
begin
  if v_me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  if not exists (
    select 1 from public.calls c where c.id=p_call_id and (c.caller_id=v_me or c.callee_id=v_me)
  ) and not exists (
    select 1 from public.call_participants cp where cp.call_id=p_call_id and cp.user_id=v_me
  ) then raise exception 'CALL_NOT_ACCESSIBLE'; end if;
  return query
  select count(q.id),avg(q.round_trip_ms),avg(q.jitter_ms),avg(q.quality_score),sum(q.packets_lost)::numeric,
         count(q.id) filter (where q.turn_used),c.reconnect_count
  from public.calls c
  left join public.call_quality_samples q on q.call_id=c.id
  where c.id=p_call_id
  group by c.reconnect_count;
end;
$$;

create or replace function private.cleanup_stale_chat_call_ephemera()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_presence integer := 0;
  v_signals integer := 0;
  v_drafts integer := 0;
  v_missed integer := 0;
begin
  update public.calls
     set status='missed',ended_at=coalesce(ended_at,now()),end_reason=coalesce(end_reason,'timeout'),ended_cleanly=true
   where status='ringing' and timeout_at<=now();
  get diagnostics v_missed = row_count;

  delete from public.conversation_presence where expires_at < now() - interval '5 minutes';
  get diagnostics v_presence = row_count;

  delete from public.call_signals s
  using public.calls c
  where c.id=s.call_id and c.ended_at is not null and c.ended_at < now()-interval '24 hours';
  get diagnostics v_signals = row_count;

  delete from public.conversation_drafts
  where updated_at < now()-interval '30 days' and content='';
  get diagnostics v_drafts = row_count;

  update public.call_push_dispatches
     set next_attempt_at=coalesce(next_attempt_at,now()+interval '5 minutes'),
         dead_letter_at=case when attempts>=5 then coalesce(dead_letter_at,now()) else dead_letter_at end,
         updated_at=now()
   where status='failed' and dead_letter_at is null;

  update public.message_push_dispatches
     set next_attempt_at=coalesce(next_attempt_at,now()+interval '5 minutes'),
         dead_letter_at=case when attempts>=5 then coalesce(dead_letter_at,now()) else dead_letter_at end,
         updated_at=now()
   where status='failed' and dead_letter_at is null;

  return jsonb_build_object('missed_calls',v_missed,'presence_deleted',v_presence,'signals_deleted',v_signals,'empty_drafts_deleted',v_drafts);
end;
$$;

revoke all on function private.cleanup_stale_chat_call_ephemera() from public, anon, authenticated;
grant execute on function private.cleanup_stale_chat_call_ephemera() to service_role;

revoke all on function public.start_call(uuid,uuid,text) from public, anon;
revoke all on function public.start_call_v2(uuid,uuid,text,uuid) from public, anon;
revoke all on function public.invite_call_participant(uuid,uuid) from public, anon;
revoke all on function public.record_call_quality_sample(uuid,text,text,text,numeric,numeric,bigint,bigint,bigint,bigint,numeric,integer,integer,bigint,text,text,boolean,numeric,jsonb) from public, anon;
revoke all on function public.record_call_network_event(uuid,text,text,text,text,jsonb) from public, anon;
revoke all on function public.get_call_quality_summary(uuid) from public, anon;

grant execute on function public.start_call(uuid,uuid,text) to authenticated;
grant execute on function public.start_call_v2(uuid,uuid,text,uuid) to authenticated;
grant execute on function public.invite_call_participant(uuid,uuid) to authenticated;
grant execute on function public.record_call_quality_sample(uuid,text,text,text,numeric,numeric,bigint,bigint,bigint,bigint,numeric,integer,integer,bigint,text,text,boolean,numeric,jsonb) to authenticated;
grant execute on function public.record_call_network_event(uuid,text,text,text,text,jsonb) to authenticated;
grant execute on function public.get_call_quality_summary(uuid) to authenticated;

alter table public.call_participants replica identity full;
alter table public.call_events replica identity full;
alter table public.call_quality_samples replica identity full;
alter table public.call_network_events replica identity full;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='call_participants') then
    alter publication supabase_realtime add table public.call_participants;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='call_events') then
    alter publication supabase_realtime add table public.call_events;
  end if;
end $$;

-- Run stale ringing/presence/signaling cleanup every five minutes when pg_cron is present.
do $$
begin
  if exists (select 1 from pg_extension where extname='pg_cron')
     and not exists (select 1 from cron.job where jobname='blink-chat-call-ephemera-cleanup') then
    perform cron.schedule(
      'blink-chat-call-ephemera-cleanup',
      '*/5 * * * *',
      'select private.cleanup_stale_chat_call_ephemera();'
    );
  end if;
end $$;
