-- BLINK activity pulse remote policy + lightweight product analytics.
-- Presentation-only: does not modify presence, points, XP, leaderboard ordering, or feed ranking.

create table if not exists public.blink_activity_pulse_config (
    id boolean primary key default true check (id),
    enabled boolean not null default true,
    community_min_per_active integer not null default 30 check (community_min_per_active between 1 and 1000),
    community_max_per_active integer not null default 50 check (community_max_per_active between community_min_per_active and 2000),
    rank_min_per_event integer not null default 10 check (rank_min_per_event between 1 and 1000),
    rank_max_per_event integer not null default 15 check (rank_max_per_event between rank_min_per_event and 2000),
    connect_tick_ms integer not null default 2800 check (connect_tick_ms between 1000 and 60000),
    rank_tick_ms integer not null default 2400 check (rank_tick_ms between 1000 and 60000),
    min_hold_ms integer not null default 2400 check (min_hold_ms between 1000 and 60000),
    rank_window_ms integer not null default 20000 check (rank_window_ms between 10000 and 300000),
    max_step integer not null default 4 check (max_step between 1 and 100),
    transition_step_multiplier integer not null default 5 check (transition_step_multiplier between 1 and 20),
    online_preview_limit integer not null default 4 check (online_preview_limit between 0 and 8),
    campus_active_threshold integer not null default 2 check (campus_active_threshold between 1 and 100000),
    campus_hot_threshold integer not null default 5 check (campus_hot_threshold >= campus_active_threshold),
    hot_rank_ups_threshold integer not null default 4 check (hot_rank_ups_threshold between 1 and 100000),
    max_units integer not null default 100000 check (max_units between 1 and 1000000),
    max_display_value integer not null default 2000000000 check (max_display_value between 1000 and 2147483647),
    updated_at timestamptz not null default now()
);

insert into public.blink_activity_pulse_config (id)
values (true)
on conflict (id) do nothing;

alter table public.blink_activity_pulse_config enable row level security;

revoke all on table public.blink_activity_pulse_config from anon, authenticated;
grant select on table public.blink_activity_pulse_config to authenticated;

drop policy if exists "authenticated can read activity pulse config" on public.blink_activity_pulse_config;
create policy "authenticated can read activity pulse config"
on public.blink_activity_pulse_config
for select
to authenticated
using (true);

create table if not exists public.blink_activity_pulse_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    surface text not null check (surface in ('connect', 'leaderboard')),
    event_type text not null check (event_type in ('impression', 'online_preview_open', 'profile_open', 'manual_refresh')),
    real_count integer not null default 0 check (real_count >= 0),
    displayed_value integer check (displayed_value is null or displayed_value >= 0),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists blink_activity_pulse_events_user_created_idx
    on public.blink_activity_pulse_events (user_id, created_at desc);
create index if not exists blink_activity_pulse_events_surface_created_idx
    on public.blink_activity_pulse_events (surface, created_at desc);

alter table public.blink_activity_pulse_events enable row level security;
revoke all on table public.blink_activity_pulse_events from anon, authenticated;

create or replace function public.record_blink_activity_pulse_event(
    p_surface text,
    p_event_type text,
    p_real_count integer default 0,
    p_displayed_value integer default null,
    p_metadata jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_user_id uuid := auth.uid();
begin
    if v_user_id is null then
        raise exception 'AUTH_REQUIRED';
    end if;

    if p_surface not in ('connect', 'leaderboard') then
        raise exception 'INVALID_SURFACE';
    end if;

    if p_event_type not in ('impression', 'online_preview_open', 'profile_open', 'manual_refresh') then
        raise exception 'INVALID_EVENT_TYPE';
    end if;

    -- Prevent accidental recomposition/retry storms from inflating analytics.
    if exists (
        select 1
        from public.blink_activity_pulse_events e
        where e.user_id = v_user_id
          and e.surface = p_surface
          and e.event_type = p_event_type
          and e.created_at >= now() - interval '10 seconds'
    ) then
        return false;
    end if;

    insert into public.blink_activity_pulse_events (
        user_id,
        surface,
        event_type,
        real_count,
        displayed_value,
        metadata
    ) values (
        v_user_id,
        p_surface,
        p_event_type,
        greatest(coalesce(p_real_count, 0), 0),
        case when p_displayed_value is null then null else greatest(p_displayed_value, 0) end,
        coalesce(p_metadata, '{}'::jsonb)
    );

    return true;
end;
$$;

revoke all on function public.record_blink_activity_pulse_event(text, text, integer, integer, jsonb)
from public, anon;
grant execute on function public.record_blink_activity_pulse_event(text, text, integer, integer, jsonb)
to authenticated;

comment on table public.blink_activity_pulse_config is
'Server-controlled presentation policy for Connect Community Activity and Leaderboard Rank Pulse.';
comment on table public.blink_activity_pulse_events is
'Rate-limited product analytics for activity-pulse impressions and interactions.';
