-- BLINK daily missions + XP integrity hardening.
-- destructive-change-reviewed: additive mission tables/functions and replacement of one XP trigger helper only.
-- rollback-plan: restore private.award_xp_from_activity from 20260919194500, drop the mission RPCs/tables/config rows.

begin;

-- Keep daily mission definitions server-owned so rewards/targets can be tuned without a new APK.
create table if not exists private.blink_daily_mission_config (
    mission_key text primary key,
    title text not null,
    description text not null,
    event_types text[] not null,
    target_count integer not null check (target_count > 0),
    coin_reward integer not null check (coin_reward >= 0),
    xp_reward integer not null check (xp_reward >= 0),
    sort_order integer not null default 0,
    is_active boolean not null default true,
    updated_at timestamptz not null default now()
);

revoke all on private.blink_daily_mission_config from public, anon, authenticated;

insert into private.blink_daily_mission_config(
    mission_key,title,description,event_types,target_count,coin_reward,xp_reward,sort_order,is_active
) values
(
    'creator_move',
    'Creator Move',
    'Create 1 post or reel today.',
    array['create_post']::text[],
    1,5,20,10,true
),
(
    'join_conversation',
    'Join the Conversation',
    'Write 3 meaningful comments or replies today.',
    array['comment','reply_comment']::text[],
    3,5,20,20,true
),
(
    'support_community',
    'Support the Community',
    'Complete 5 likes, saves, shares or comment likes today.',
    array['like_post','save_post','share_post','like_comment']::text[],
    5,5,20,30,true
),
(
    'discover_blink',
    'Discover BLINK',
    'Explore 5 new posts or reels today.',
    array['qualified_view']::text[],
    5,5,20,40,true
)
on conflict (mission_key) do update
set title=excluded.title,
    description=excluded.description,
    event_types=excluded.event_types,
    target_count=excluded.target_count,
    coin_reward=excluded.coin_reward,
    xp_reward=excluded.xp_reward,
    sort_order=excluded.sort_order,
    is_active=excluded.is_active,
    updated_at=now();

create table if not exists private.blink_daily_mission_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    event_type text not null,
    event_key text not null,
    created_at timestamptz not null default now(),
    unique(user_id, event_key)
);

create index if not exists blink_daily_mission_events_user_created_idx
    on private.blink_daily_mission_events(user_id, created_at desc, event_type);

revoke all on private.blink_daily_mission_events from public, anon, authenticated;

create table if not exists public.blink_daily_mission_claims (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(id) on delete cascade,
    mission_date date not null,
    mission_key text not null,
    coin_reward integer not null check (coin_reward >= 0),
    xp_reward integer not null check (xp_reward >= 0),
    claimed_at timestamptz not null default now(),
    unique(user_id, mission_date, mission_key)
);

create index if not exists blink_daily_mission_claims_user_date_idx
    on public.blink_daily_mission_claims(user_id, mission_date desc, claimed_at desc);

alter table public.blink_daily_mission_claims enable row level security;
drop policy if exists blink_daily_mission_claims_read_own on public.blink_daily_mission_claims;
create policy blink_daily_mission_claims_read_own
on public.blink_daily_mission_claims
for select
to authenticated
using (user_id = (select auth.uid()));

revoke all on public.blink_daily_mission_claims from anon, authenticated;
grant select on public.blink_daily_mission_claims to authenticated;

-- XP source integrity: comments use author_id, and reversible interactions key XP by the target
-- instead of a disposable row id. This prevents unlike/re-like and unfollow/refollow farming.
create or replace function private.award_xp_from_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_row jsonb := to_jsonb(new);
    v_user uuid;
    v_source text;
    v_event text;
    v_key text;
    v_parent text;
    v_comment_text text;
begin
    v_user := coalesce(
        nullif(v_row->>'user_id','')::uuid,
        nullif(v_row->>'author_id','')::uuid,
        nullif(v_row->>'follower_id','')::uuid,
        nullif(v_row->>'sender_id','')::uuid,
        nullif(v_row->>'viewer_id','')::uuid
    );

    if v_user is null then return new; end if;

    v_parent := coalesce(v_row->>'parent_comment_id', v_row->>'parent_id', '');

    if tg_table_name = 'feed_posts' then
        v_event := 'create_post';
        v_source := coalesce(v_row->>'id','');
    elsif tg_table_name = 'post_likes' then
        v_event := 'like_post';
        v_source := coalesce(v_row->>'post_id','');
    elsif tg_table_name = 'comments' then
        v_event := case when v_parent <> '' then 'reply_comment' else 'comment' end;
        v_source := coalesce(v_row->>'id','');
        v_comment_text := coalesce(v_row->>'content','');
        -- Tiny filler comments should not earn progression XP.
        if char_length(regexp_replace(v_comment_text, '[[:space:]]', '', 'g')) < 3 then
            return new;
        end if;
    elsif tg_table_name = 'comment_likes' then
        v_event := 'like_comment';
        v_source := coalesce(v_row->>'comment_id','');
    elsif tg_table_name = 'post_bookmarks' then
        v_event := 'save_post';
        v_source := coalesce(v_row->>'post_id','');
    elsif tg_table_name = 'post_shares' then
        v_event := 'share_post';
        v_source := coalesce(v_row->>'post_id','');
    elsif tg_table_name = 'follows' then
        v_event := 'follow_user';
        v_source := coalesce(v_row->>'following_id','');
    elsif tg_table_name = 'post_views' then
        v_event := 'qualified_view';
        v_source := coalesce(v_row->>'post_id','');
    else
        return new;
    end if;

    if coalesce(v_source,'') = '' then return new; end if;

    -- Do not let users farm progression from their own content.
    if tg_table_name in ('post_likes', 'post_bookmarks', 'post_shares', 'post_views') then
        if exists (
            select 1
            from public.feed_posts fp
            where fp.id::text = coalesce(v_row->>'post_id', '')
              and fp.user_id = v_user
        ) then
            return new;
        end if;
    end if;

    if tg_table_name = 'comment_likes' then
        if exists (
            select 1
            from public.comments c
            where c.id::text = coalesce(v_row->>'comment_id', '')
              and c.author_id = v_user
        ) then
            return new;
        end if;
    end if;

    if tg_table_name = 'follows'
       and coalesce(v_row->>'following_id', '') = v_user::text then
        return new;
    end if;

    v_key := 'activity:' || v_event || ':' || v_source || ':' || v_user::text;

    -- Mission progress is recorded independently of XP credit. This matters after
    -- a user reaches the repeatable-XP soft cap: genuine mission activity can
    -- still complete a mission without granting extra repeatable XP.
    insert into private.blink_daily_mission_events(user_id,event_type,event_key)
    values(v_user,v_event,v_key)
    on conflict(user_id,event_key) do nothing;

    perform private.award_xp(
        v_user,
        v_event,
        v_key,
        tg_table_name,
        v_source,
        null
    );
    return new;
end;
$$;

revoke all on function private.award_xp_from_activity() from public, anon, authenticated;

create or replace function public.get_my_daily_missions()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_user uuid := auth.uid();
    v_day date := (now() at time zone 'UTC')::date;
    v_start timestamptz := date_trunc('day', now() at time zone 'UTC') at time zone 'UTC';
    v_end timestamptz := (date_trunc('day', now() at time zone 'UTC') + interval '1 day') at time zone 'UTC';
    v_missions jsonb;
    v_claimed_count integer := 0;
    v_completed_count integer := 0;
begin
    if v_user is null then raise exception 'AUTH_REQUIRED'; end if;

    with mission_rows as (
        select
            c.mission_key,
            c.title,
            c.description,
            c.target_count,
            c.coin_reward,
            c.xp_reward,
            c.sort_order,
            least(
                c.target_count,
                (
                    select count(*)::integer
                    from private.blink_daily_mission_events x
                    where x.user_id = v_user
                      and x.event_type = any(c.event_types)
                      and x.created_at >= v_start
                      and x.created_at < v_end
                )
            ) as progress,
            exists(
                select 1
                from public.blink_daily_mission_claims mc
                where mc.user_id = v_user
                  and mc.mission_date = v_day
                  and mc.mission_key = c.mission_key
            ) as claimed
        from private.blink_daily_mission_config c
        where c.is_active = true
    ),
    aggregated as (
        select
            coalesce(
                jsonb_agg(
                    jsonb_build_object(
                        'key', mission_key,
                        'title', title,
                        'description', description,
                        'progress', progress,
                        'target', target_count,
                        'coin_reward', coin_reward,
                        'xp_reward', xp_reward,
                        'completed', progress >= target_count,
                        'claimed', claimed,
                        'claimable', progress >= target_count and not claimed
                    )
                    order by sort_order, mission_key
                ),
                '[]'::jsonb
            ) as missions,
            count(*) filter(where claimed)::integer as claimed_count,
            count(*) filter(where progress >= target_count)::integer as completed_count,
            coalesce(sum(coin_reward) filter(where not claimed),0)::integer as coins_remaining,
            coalesce(sum(xp_reward) filter(where not claimed),0)::integer as xp_remaining
        from mission_rows
    )
    select missions, claimed_count, completed_count
      into v_missions, v_claimed_count, v_completed_count
      from aggregated;

    return jsonb_build_object(
        'date', v_day,
        'missions', coalesce(v_missions,'[]'::jsonb),
        'claimed_count', coalesce(v_claimed_count,0),
        'completed_count', coalesce(v_completed_count,0),
        'daily_coin_max', coalesce((select sum(coin_reward) from private.blink_daily_mission_config where is_active),0),
        'daily_xp_max', coalesce((select sum(xp_reward) from private.blink_daily_mission_config where is_active),0)
    );
end
$$;

revoke all on function public.get_my_daily_missions() from public, anon;
grant execute on function public.get_my_daily_missions() to authenticated;

create or replace function public.claim_daily_mission(p_mission_key text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user uuid := auth.uid();
    v_day date := (now() at time zone 'UTC')::date;
    v_start timestamptz := date_trunc('day', now() at time zone 'UTC') at time zone 'UTC';
    v_end timestamptz := (date_trunc('day', now() at time zone 'UTC') + interval '1 day') at time zone 'UTC';
    v_config private.blink_daily_mission_config%rowtype;
    v_progress integer := 0;
    v_balance bigint := 0;
    v_awarded_xp integer := 0;
    v_total_xp bigint := 0;
    v_level integer := 1;
begin
    if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
    if coalesce(trim(p_mission_key),'') = '' then raise exception 'MISSION_REQUIRED'; end if;

    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(v_user::text)::bigint);

    select * into v_config
    from private.blink_daily_mission_config
    where mission_key = trim(p_mission_key)
      and is_active = true;

    if not found then raise exception 'MISSION_NOT_FOUND'; end if;

    if exists(
        select 1
        from public.blink_daily_mission_claims
        where user_id = v_user
          and mission_date = v_day
          and mission_key = v_config.mission_key
    ) then
        select coalesce(floor(spendable_coin_balance),0)::bigint
          into v_balance
          from public.user_balances
         where user_id = v_user;
        select coalesce(total_xp,0),coalesce(xp_level,1)
          into v_total_xp,v_level
          from public.profiles where id=v_user;
        return jsonb_build_object(
            'success',true,'already_claimed',true,'mission_key',v_config.mission_key,
            'coin_reward',0,'xp_reward',0,'balance',coalesce(v_balance,0),
            'total_xp',coalesce(v_total_xp,0),'xp_level',coalesce(v_level,1)
        );
    end if;

    select count(*)::integer into v_progress
    from private.blink_daily_mission_events x
    where x.user_id = v_user
      and x.event_type = any(v_config.event_types)
      and x.created_at >= v_start
      and x.created_at < v_end;

    if v_progress < v_config.target_count then
        raise exception 'MISSION_NOT_COMPLETE';
    end if;

    insert into public.blink_daily_mission_claims(
        user_id,mission_date,mission_key,coin_reward,xp_reward
    ) values (
        v_user,v_day,v_config.mission_key,v_config.coin_reward,v_config.xp_reward
    );

    insert into public.user_balances(user_id,spendable_coin_balance,updated_at)
    values(v_user,0,now())
    on conflict(user_id) do nothing;

    update public.user_balances
       set spendable_coin_balance = spendable_coin_balance + v_config.coin_reward,
           updated_at = now()
     where user_id = v_user
    returning floor(spendable_coin_balance)::bigint into v_balance;

    perform set_config('blink.coin_sync_bypass','1',true);
    insert into public.game_profiles(user_id,coins,updated_at)
    values(v_user,v_balance,now())
    on conflict(user_id) do update
      set coins=excluded.coins,updated_at=now();
    perform set_config('blink.coin_sync_bypass','0',true);

    insert into public.blink_coin_transactions(
        user_id,kind,item_name,amount,balance_after,metadata
    ) values (
        v_user,
        'DAILY_MISSION',
        v_config.title,
        v_config.coin_reward,
        v_balance,
        jsonb_build_object('mission_key',v_config.mission_key,'mission_date',v_day)
    );

    v_awarded_xp := private.award_xp(
        v_user,
        'daily_mission',
        'daily_mission:' || v_day::text || ':' || v_config.mission_key,
        'daily_mission',
        v_config.mission_key,
        v_config.xp_reward
    );

    select coalesce(total_xp,0),coalesce(xp_level,1)
      into v_total_xp,v_level
      from public.profiles where id=v_user;

    return jsonb_build_object(
        'success',true,
        'already_claimed',false,
        'mission_key',v_config.mission_key,
        'coin_reward',v_config.coin_reward,
        'xp_reward',v_awarded_xp,
        'balance',v_balance,
        'total_xp',coalesce(v_total_xp,0),
        'xp_level',coalesce(v_level,1)
    );
end
$$;

revoke all on function public.claim_daily_mission(text) from public, anon;
grant execute on function public.claim_daily_mission(text) to authenticated;

commit;
