BEGIN;

-- Remove default PUBLIC execution from privileged application functions.
REVOKE EXECUTE ON FUNCTION public.activity_from_bookmark() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.activity_from_connection() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.activity_from_post_comment() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.activity_from_post_like() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.award_interaction_points() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.award_message_points() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.award_save_points() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.award_share_points() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.notify_follow_created() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.notify_message_created() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalc_comment_like_count() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalc_feed_comment_count() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalc_feed_like_count() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalc_poll_option_vote_count() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalc_story_like_count() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalc_story_view_count() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_follow_counts() FROM PUBLIC;

REVOKE EXECUTE ON FUNCTION public.accept_connection_request(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.approve_circle_request(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.bookmark_post(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.cancel_connection_request(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_marketplace_order(uuid,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.decline_connection_request(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.delete_post(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.follow_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_following_feed(integer,timestamptz) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.join_study_circle(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.leave_study_circle(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.like_comment(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.like_post(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_game_session(text,integer,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_post_view(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_post_view(uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.remove_circle_member(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.request_to_join_circle(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.send_connection_request(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.send_message(text,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.send_message(uuid,text,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.share_post(uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.submit_verification_request(text,jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.unbookmark_post(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.unfollow_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.unlike_comment(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.unlike_post(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.vote_in_poll(uuid,uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.accept_connection_request(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_circle_request(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bookmark_post(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_connection_request(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_marketplace_order(uuid,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.decline_connection_request(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_post(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.follow_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_following_feed(integer,timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.join_study_circle(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.leave_study_circle(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.like_comment(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.like_post(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_game_session(text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_post_view(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_post_view(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.remove_circle_member(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.request_to_join_circle(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_connection_request(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_message(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_message(uuid,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.share_post(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_verification_request(text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unbookmark_post(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unfollow_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unlike_comment(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unlike_post(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.vote_in_poll(uuid,uuid) TO authenticated;

-- Cover foreign keys identified by the Supabase performance advisor.
CREATE INDEX IF NOT EXISTS conversations_created_by_idx ON public.conversations (created_by);
CREATE INDEX IF NOT EXISTS interactions_post_id_idx ON public.interactions (post_id);
CREATE INDEX IF NOT EXISTS leaderboard_snapshots_user_id_idx ON public.leaderboard_snapshots (user_id);
CREATE INDEX IF NOT EXISTS messages_reply_to_idx ON public.messages (reply_to);
CREATE INDEX IF NOT EXISTS notifications_actor_id_idx ON public.notifications (actor_id);
CREATE INDEX IF NOT EXISTS notifications_post_id_idx ON public.notifications (post_id);
CREATE INDEX IF NOT EXISTS poll_votes_user_id_idx ON public.poll_votes (user_id);
CREATE INDEX IF NOT EXISTS profile_skills_skill_id_idx ON public.profile_skills (skill_id);
CREATE INDEX IF NOT EXISTS skill_endorsements_endorser_user_id_idx ON public.skill_endorsements (endorser_user_id);
CREATE INDEX IF NOT EXISTS statuses_user_id_idx ON public.statuses (user_id);
CREATE INDEX IF NOT EXISTS story_interactions_user_id_idx ON public.story_interactions (user_id);
CREATE INDEX IF NOT EXISTS story_likes_user_id_idx ON public.story_likes (user_id);
CREATE INDEX IF NOT EXISTS story_reactions_user_id_idx ON public.story_reactions (user_id);
CREATE INDEX IF NOT EXISTS story_replies_user_id_idx ON public.story_replies (user_id);
CREATE INDEX IF NOT EXISTS story_views_user_id_idx ON public.story_views (user_id);
CREATE INDEX IF NOT EXISTS study_circle_requests_user_id_idx ON public.study_circle_requests (user_id);
CREATE INDEX IF NOT EXISTS token_transactions_post_id_idx ON public.token_transactions (post_id);
CREATE INDEX IF NOT EXISTS token_transactions_recipient_id_idx ON public.token_transactions (recipient_id);
CREATE INDEX IF NOT EXISTS token_transactions_sender_id_idx ON public.token_transactions (sender_id);
CREATE INDEX IF NOT EXISTS verification_requests_reviewed_by_idx ON public.verification_requests (reviewed_by);
CREATE INDEX IF NOT EXISTS verifications_user_id_idx ON public.verifications (user_id);

-- Remove exact duplicate indexes while retaining the existing canonical copy.
DROP INDEX IF EXISTS public.idx_comment_likes_comment;
DROP INDEX IF EXISTS public.fcm_tokens_user_token_uidx;
DROP INDEX IF EXISTS public.idx_feed_posts_created_at;
DROP INDEX IF EXISTS public.idx_follows_following;
DROP INDEX IF EXISTS public.messages_conversation_created_idx;
DROP INDEX IF EXISTS public.post_bookmarks_post_idx;
DROP INDEX IF EXISTS public.idx_post_likes_post;
DROP INDEX IF EXISTS public.idx_post_likes_user;
DROP INDEX IF EXISTS public.idx_profiles_username_lower;
DROP INDEX IF EXISTS public.study_circles_owner_idx;

COMMIT;
