create table if not exists public.calls (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  caller_id uuid not null references public.profiles(id) on delete cascade,
  callee_id uuid not null references public.profiles(id) on delete cascade,
  call_type text not null check (call_type in ('audio','video')),
  status text not null default 'ringing' check (status in ('ringing','connecting','connected','declined','busy','missed','cancelled','ended','failed')),
  created_at timestamptz not null default now(),
  ringing_at timestamptz not null default now(),
  answered_at timestamptz,
  connected_at timestamptz,
  ended_at timestamptz,
  timeout_at timestamptz not null default (now() + interval '45 seconds'),
  ended_by uuid references public.profiles(id) on delete set null,
  end_reason text,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  constraint calls_distinct_users check (caller_id <> callee_id)
);

create index if not exists calls_conversation_created_idx on public.calls(conversation_id, created_at desc);
create index if not exists calls_caller_status_idx on public.calls(caller_id, status, created_at desc);
create index if not exists calls_callee_status_idx on public.calls(callee_id, status, created_at desc);
create index if not exists calls_timeout_idx on public.calls(timeout_at) where status = 'ringing';

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.calls(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check (kind in ('offer','answer','ice','renegotiate','hangup')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists call_signals_call_id_idx on public.call_signals(call_id, id);

create table if not exists public.call_push_dispatches (
  call_id uuid not null references public.calls(id) on delete cascade,
  event text not null,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'sending' check (status in ('sending','sent','failed')),
  attempts integer not null default 1 check (attempts > 0),
  last_error text,
  updated_at timestamptz not null default now(),
  primary key (call_id, event, target_user_id)
);

alter table public.calls enable row level security;
alter table public.call_signals enable row level security;
alter table public.call_push_dispatches enable row level security;

drop policy if exists "participants can read calls" on public.calls;
create policy "participants can read calls"
on public.calls for select
to authenticated
using ((select auth.uid()) = caller_id or (select auth.uid()) = callee_id);

drop policy if exists "participants can read call signals" on public.call_signals;
create policy "participants can read call signals"
on public.call_signals for select
to authenticated
using (
  exists (
    select 1 from public.calls c
    where c.id = call_signals.call_id
      and ((select auth.uid()) = c.caller_id or (select auth.uid()) = c.callee_id)
  )
);

drop policy if exists "participants can send own call signals" on public.call_signals;
create policy "participants can send own call signals"
on public.call_signals for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1 from public.calls c
    where c.id = call_signals.call_id
      and c.status in ('ringing','connecting','connected')
      and ((select auth.uid()) = c.caller_id or (select auth.uid()) = c.callee_id)
  )
);

revoke all on public.call_push_dispatches from anon, authenticated;
grant select on public.calls to authenticated;
grant select, insert on public.call_signals to authenticated;
grant usage, select on sequence public.call_signals_id_seq to authenticated;

create or replace function public.start_call(
  p_conversation_id uuid,
  p_callee_id uuid,
  p_call_type text
)
returns public.calls
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_caller_id uuid := auth.uid();
  v_call public.calls;
begin
  if v_caller_id is null then
    raise exception 'AUTHENTICATION_REQUIRED';
  end if;
  if p_callee_id is null or p_callee_id = v_caller_id then
    raise exception 'INVALID_CALLEE';
  end if;
  if p_call_type not in ('audio','video') then
    raise exception 'INVALID_CALL_TYPE';
  end if;
  if not exists (
    select 1 from public.conversation_participants cp
    where cp.conversation_id = p_conversation_id and cp.user_id = v_caller_id
  ) or not exists (
    select 1 from public.conversation_participants cp
    where cp.conversation_id = p_conversation_id and cp.user_id = p_callee_id
  ) then
    raise exception 'NOT_CONVERSATION_PARTICIPANT';
  end if;
  if exists (
    select 1 from public.blocks b
    where (b.blocker_id = v_caller_id and b.blocked_id = p_callee_id)
       or (b.blocker_id = p_callee_id and b.blocked_id = v_caller_id)
  ) then
    raise exception 'CALL_BLOCKED';
  end if;

  update public.calls
     set status = 'missed', ended_at = now(), end_reason = 'timeout'
   where status = 'ringing' and timeout_at <= now()
     and (caller_id in (v_caller_id, p_callee_id) or callee_id in (v_caller_id, p_callee_id));

  if exists (
    select 1 from public.calls c
    where c.status in ('ringing','connecting','connected')
      and (c.caller_id in (v_caller_id, p_callee_id) or c.callee_id in (v_caller_id, p_callee_id))
  ) then
    raise exception 'USER_BUSY';
  end if;

  insert into public.calls (conversation_id, caller_id, callee_id, call_type)
  values (p_conversation_id, v_caller_id, p_callee_id, p_call_type)
  returning * into v_call;

  return v_call;
end;
$$;

create or replace function public.answer_call(p_call_id uuid)
returns public.calls
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_call public.calls;
begin
  if v_user_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  select * into v_call from public.calls where id = p_call_id for update;
  if not found or v_call.callee_id <> v_user_id then raise exception 'CALL_NOT_FOUND'; end if;
  if v_call.status <> 'ringing' then raise exception 'CALL_NOT_RINGING'; end if;
  if v_call.timeout_at <= now() then
    update public.calls set status='missed', ended_at=now(), end_reason='timeout' where id=p_call_id returning * into v_call;
    return v_call;
  end if;
  update public.calls set status='connecting', answered_at=coalesce(answered_at,now()) where id=p_call_id returning * into v_call;
  return v_call;
end;
$$;

create or replace function public.decline_call(p_call_id uuid)
returns public.calls
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_call public.calls;
begin
  if v_user_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  select * into v_call from public.calls where id=p_call_id for update;
  if not found or v_call.callee_id <> v_user_id then raise exception 'CALL_NOT_FOUND'; end if;
  if v_call.status in ('declined','missed','cancelled','ended','failed') then return v_call; end if;
  update public.calls set status='declined', ended_at=now(), ended_by=v_user_id, end_reason='declined' where id=p_call_id returning * into v_call;
  return v_call;
end;
$$;

create or replace function public.mark_call_connected(p_call_id uuid)
returns public.calls
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_call public.calls;
begin
  if v_user_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  select * into v_call from public.calls where id=p_call_id for update;
  if not found or (v_call.caller_id <> v_user_id and v_call.callee_id <> v_user_id) then raise exception 'CALL_NOT_FOUND'; end if;
  if v_call.status in ('ringing','connecting') then
    update public.calls set status='connected', connected_at=coalesce(connected_at,now()), answered_at=coalesce(answered_at,now()) where id=p_call_id returning * into v_call;
  end if;
  return v_call;
end;
$$;

create or replace function public.end_call(p_call_id uuid, p_reason text default 'ended')
returns public.calls
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_call public.calls;
  v_status text;
  v_reason text := left(coalesce(nullif(btrim(p_reason),''),'ended'),120);
begin
  if v_user_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  select * into v_call from public.calls where id=p_call_id for update;
  if not found or (v_call.caller_id <> v_user_id and v_call.callee_id <> v_user_id) then raise exception 'CALL_NOT_FOUND'; end if;
  if v_call.status in ('declined','missed','cancelled','ended','failed') then return v_call; end if;
  v_status := case
    when v_call.status='ringing' and v_user_id=v_call.caller_id then 'cancelled'
    when v_call.status='ringing' and v_user_id=v_call.callee_id then 'declined'
    when v_reason='failed' then 'failed'
    else 'ended'
  end;
  update public.calls
     set status=v_status,
         ended_at=now(),
         ended_by=v_user_id,
         end_reason=v_reason,
         duration_seconds=greatest(0, floor(extract(epoch from (now() - coalesce(connected_at, answered_at, created_at))))::integer)
   where id=p_call_id
   returning * into v_call;
  return v_call;
end;
$$;

create or replace function public.expire_call(p_call_id uuid)
returns public.calls
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_call public.calls;
begin
  if v_user_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  select * into v_call from public.calls where id=p_call_id for update;
  if not found or (v_call.caller_id <> v_user_id and v_call.callee_id <> v_user_id) then raise exception 'CALL_NOT_FOUND'; end if;
  if v_call.status='ringing' and v_call.timeout_at <= now() then
    update public.calls set status='missed', ended_at=now(), end_reason='timeout' where id=p_call_id returning * into v_call;
  end if;
  return v_call;
end;
$$;

revoke all on function public.start_call(uuid,uuid,text) from public, anon;
revoke all on function public.answer_call(uuid) from public, anon;
revoke all on function public.decline_call(uuid) from public, anon;
revoke all on function public.mark_call_connected(uuid) from public, anon;
revoke all on function public.end_call(uuid,text) from public, anon;
revoke all on function public.expire_call(uuid) from public, anon;
grant execute on function public.start_call(uuid,uuid,text) to authenticated;
grant execute on function public.answer_call(uuid) to authenticated;
grant execute on function public.decline_call(uuid) to authenticated;
grant execute on function public.mark_call_connected(uuid) to authenticated;
grant execute on function public.end_call(uuid,text) to authenticated;
grant execute on function public.expire_call(uuid) to authenticated;

alter table public.calls replica identity full;
alter table public.call_signals replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='calls'
  ) then
    alter publication supabase_realtime add table public.calls;
  end if;
  if not exists (
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='call_signals'
  ) then
    alter publication supabase_realtime add table public.call_signals;
  end if;
end $$;
